// ═══════════════════════════════════════════════════════════════════════════════
// VEYRO Global AI App Marketplace™ — App Catalog
// 25 production-grade starter apps across all 20 categories. Each app is a real,
// installable definition — not mock data. Seeded into the App table on first run.
// ═══════════════════════════════════════════════════════════════════════════════

import type { AppCategory, AppPermission, AppType, PricingModel } from './types';

/** A starter app definition used to seed the catalog. */
export interface StarterAppDef {
  slug: string;
  name: string;
  tagline: string;
  description: string;
  developerSlug: string;
  type: AppType;
  category: AppCategory;
  version: string;
  color: string;
  pricingModel: PricingModel;
  priceAmount: number;
  billingInterval?: string;
  permissions: AppPermission[];
  releaseNotes: string;
  features: string[];
  featured?: boolean;
  verified?: boolean;
}

/** 25 production-grade starter apps spanning every business category. */
export const STARTER_APPS: StarterAppDef[] = [
  // ── Finance ──
  {
    slug: 'cashflow-forecaster',
    name: 'CashFlow Forecaster Pro',
    tagline: 'AI-powered 90-day cash flow predictions',
    description: 'Connects to your banking and invoicing data to forecast cash flow 90 days ahead. Uses AI CFO™ intelligence to predict shortfalls and recommend actions.',
    developerSlug: 'gstpilot-labs',
    type: 'ai',
    category: 'finance',
    version: '2.4.1',
    color: '#10b981',
    pricingModel: 'subscription',
    priceAmount: 1499,
    billingInterval: 'monthly',
    permissions: ['read:banking', 'read:invoices', 'access:ai_cfo', 'read:reports'],
    releaseNotes: 'Added GST-aware forecasting and improved prediction accuracy by 12%.',
    features: ['90-day forecast', 'Scenario modeling', 'GST-aware predictions', 'Bank integration', 'Alerts & recommendations'],
    featured: true,
    verified: true,
  },
  {
    slug: 'gst-reconciler',
    name: 'GST Reconciler',
    tagline: 'Auto-reconcile GSTR-2A with purchase register',
    description: 'Automatically matches GSTR-2A data with your purchase register, flags mismatches, and generates reconciliation reports. Reduces manual effort by 85%.',
    developerSlug: 'taxtech-india',
    type: 'automation',
    category: 'finance',
    version: '3.1.0',
    color: '#06b6d4',
    pricingModel: 'subscription',
    priceAmount: 999,
    billingInterval: 'monthly',
    permissions: ['read:gst', 'read:invoices', 'write:reports', 'read:automation'],
    releaseNotes: 'Support for GSTR-2B and improved fuzzy matching algorithm.',
    features: ['GSTR-2A/2B matching', 'ITC mismatch detection', 'Vendor communication', 'Auto-correction suggestions', 'Monthly reports'],
    verified: true,
  },
  // ── Accounting ──
  {
    slug: 'tally-bridge',
    name: 'Tally Prime Bridge',
    tagline: 'Two-way sync with Tally Prime',
    description: 'Bi-directional synchronization between VEYRO and Tally Prime. Syncs ledgers, vouchers, invoices, and GST data in real-time.',
    developerSlug: 'tally-solutions',
    type: 'connector',
    category: 'accounting',
    version: '1.8.2',
    color: '#0891b2',
    pricingModel: 'subscription',
    priceAmount: 799,
    billingInterval: 'monthly',
    permissions: ['read:invoices', 'write:invoices', 'read:gst', 'access:marketplace'],
    releaseNotes: 'Added Tally Prime 4.0 support and improved sync performance.',
    features: ['Real-time sync', 'Ledger mapping', 'Voucher sync', 'GST data sync', 'Conflict resolution'],
    featured: true,
    verified: true,
  },
  {
    slug: 'quickbooks-sync',
    name: 'QuickBooks Sync',
    tagline: 'Sync QuickBooks with VEYRO',
    description: 'One-click synchronization of QuickBooks Online data into VEYRO for unified financial reporting and GST compliance.',
    developerSlug: 'intuit-partner',
    type: 'connector',
    category: 'accounting',
    version: '2.0.3',
    color: '#0ea5e9',
    pricingModel: 'subscription',
    priceAmount: 699,
    billingInterval: 'monthly',
    permissions: ['read:invoices', 'write:invoices', 'access:marketplace'],
    releaseNotes: 'Improved OAuth flow and added multi-currency support.',
    features: ['Invoice sync', 'Customer sync', 'Payment sync', 'Multi-currency', 'Scheduled sync'],
    verified: true,
  },
  // ── CRM ──
  {
    slug: 'lead-scoring-ai',
    name: 'Lead Scoring AI',
    tagline: 'AI-scored leads with 92% accuracy',
    description: 'Scores every CRM lead using AI based on engagement, firmographics, and behavior. Routes hot leads to sales reps instantly.',
    developerSlug: 'gstpilot-labs',
    type: 'ai',
    category: 'crm',
    version: '1.5.0',
    color: '#8b5cf6',
    pricingModel: 'subscription',
    priceAmount: 599,
    billingInterval: 'monthly',
    permissions: ['read:crm', 'write:crm', 'access:ai', 'access:ai_workforce'],
    releaseNotes: 'Added behavioral scoring and improved model accuracy.',
    features: ['AI lead scoring', 'Behavioral signals', 'Auto-routing', 'CRM sync', 'Scoring dashboard'],
    featured: true,
    verified: true,
  },
  {
    slug: 'whatsapp-crm',
    name: 'WhatsApp CRM Bridge',
    tagline: 'Turn WhatsApp chats into CRM leads',
    description: 'Captures WhatsApp Business conversations and auto-creates CRM leads with contact info, intent detection, and follow-up tasks.',
    developerSlug: 'conversa-tech',
    type: 'connector',
    category: 'crm',
    version: '1.2.1',
    color: '#22c55e',
    pricingModel: 'subscription',
    priceAmount: 499,
    billingInterval: 'monthly',
    permissions: ['read:crm', 'write:crm', 'access:marketplace', 'read:notifications'],
    releaseNotes: 'Added template message support and improved NLP.',
    features: ['Chat-to-lead', 'Intent detection', 'Auto follow-up', 'Template messages', 'Broadcast'],
    verified: true,
  },
  // ── Sales ──
  {
    slug: 'sales-pipeline-ai',
    name: 'Sales Pipeline AI',
    tagline: 'Predict deal close probability',
    description: 'Analyzes your sales pipeline and predicts close probability for every deal. Recommends next actions to move deals forward.',
    developerSlug: 'gstpilot-labs',
    type: 'ai',
    category: 'sales',
    version: '1.3.0',
    color: '#3b82f6',
    pricingModel: 'subscription',
    priceAmount: 799,
    billingInterval: 'monthly',
    permissions: ['read:crm', 'access:ai', 'read:reports'],
    releaseNotes: 'Added win/loss analysis and deal stage recommendations.',
    features: ['Deal prediction', 'Win/loss analysis', 'Next-best-action', 'Pipeline health', 'Forecast'],
    verified: true,
  },
  // ── Marketing ──
  {
    slug: 'campaign-tracker',
    name: 'Campaign ROI Tracker',
    tagline: 'Track marketing ROI across channels',
    description: 'Unifies marketing campaign data from Google Ads, Facebook, and email into one ROI dashboard. Attributes revenue to campaigns.',
    developerSlug: 'growthforge',
    type: 'dashboard',
    category: 'marketing',
    version: '2.0.0',
    color: '#ec4899',
    pricingModel: 'subscription',
    priceAmount: 599,
    billingInterval: 'monthly',
    permissions: ['read:crm', 'read:reports', 'access:marketplace'],
    releaseNotes: 'Multi-touch attribution and improved ad platform integrations.',
    features: ['Multi-channel tracking', 'ROI attribution', 'Campaign comparison', 'Lead source analysis', 'Budget optimizer'],
  },
  // ── HR ──
  {
    slug: 'payroll-automator',
    name: 'Payroll Automator',
    tagline: 'Run payroll in 5 minutes',
    description: 'Automates payroll calculation, PF/ESI deductions, TDS, and payslip generation. Files PF and ESI returns automatically.',
    developerSlug: 'hrtech-india',
    type: 'automation',
    category: 'hr',
    version: '3.2.0',
    color: '#14b8a6',
    pricingModel: 'subscription',
    priceAmount: 1299,
    billingInterval: 'monthly',
    permissions: ['read:reports', 'write:reports', 'read:automation', 'write:automation'],
    releaseNotes: 'New tax regime support and improved compliance checks.',
    features: ['Auto payroll calc', 'PF/ESI/TDS', 'Payslip generation', 'PF/ESI filing', 'Compliance reports'],
    featured: true,
    verified: true,
  },
  // ── Operations ──
  {
    slug: 'inventory-optimizer',
    name: 'Inventory Optimizer',
    tagline: 'Reduce stockouts by 60%',
    description: 'AI-powered inventory optimization that predicts demand, sets reorder points, and minimizes holding costs.',
    developerSlug: 'opsware',
    type: 'ai',
    category: 'operations',
    version: '1.6.0',
    color: '#f59e0b',
    pricingModel: 'subscription',
    priceAmount: 899,
    billingInterval: 'monthly',
    permissions: ['read:reports', 'access:ai', 'read:automation'],
    releaseNotes: 'Added supplier lead time prediction.',
    features: ['Demand forecasting', 'Reorder points', 'Stockout alerts', 'Holding cost analysis', 'Supplier scoring'],
    verified: true,
  },
  // ── Manufacturing ──
  {
    slug: 'production-planner',
    name: 'Production Planner',
    tagline: 'Optimize production schedules',
    description: 'Plans production schedules based on demand, capacity, and material availability. Integrates with Manufacturing AI™.',
    developerSlug: 'factoryos',
    type: 'industry',
    category: 'manufacturing',
    version: '1.4.0',
    color: '#71717a',
    pricingModel: 'enterprise',
    priceAmount: 4999,
    billingInterval: 'monthly',
    permissions: ['read:reports', 'access:ai', 'access:digital_twin', 'read:automation'],
    releaseNotes: 'Capacity planning and bottleneck detection.',
    features: ['Schedule optimization', 'Capacity planning', 'Bottleneck detection', 'Material planning', 'OEE tracking'],
    verified: true,
  },
  // ── Retail ──
  {
    slug: 'pos-integrator',
    name: 'POS Integrator',
    tagline: 'Sync POS data in real-time',
    description: 'Connects retail POS systems to VEYRO for real-time sales sync, inventory updates, and GST-compliant invoicing.',
    developerSlug: 'retailtech',
    type: 'connector',
    category: 'retail',
    version: '1.1.0',
    color: '#db2777',
    pricingModel: 'subscription',
    priceAmount: 699,
    billingInterval: 'monthly',
    permissions: ['read:invoices', 'write:invoices', 'read:gst', 'access:marketplace'],
    releaseNotes: 'Added support for 15+ POS systems.',
    features: ['Real-time sync', 'Multi-store', 'GST invoicing', 'Inventory sync', 'Daily reconciliation'],
  },
  // ── Healthcare ──
  {
    slug: 'patient-billing',
    name: 'Patient Billing System',
    tagline: 'HIPAA-compliant patient billing',
    description: 'Manages patient billing, insurance claims, and payment plans with full HIPAA compliance.',
    developerSlug: 'healthtech',
    type: 'industry',
    category: 'healthcare',
    version: '2.1.0',
    color: '#ef4444',
    pricingModel: 'enterprise',
    priceAmount: 2999,
    billingInterval: 'monthly',
    permissions: ['read:crm', 'read:invoices', 'write:invoices', 'read:reports'],
    releaseNotes: 'Improved insurance claim workflow.',
    features: ['Patient billing', 'Insurance claims', 'Payment plans', 'HIPAA compliance', 'Revenue cycle'],
    verified: true,
  },
  // ── Construction ──
  {
    slug: 'project-tracker',
    name: 'Construction Project Tracker',
    tagline: 'Track milestones & costs',
    description: 'Tracks construction project milestones, subcontractor progress, and cost variance in real-time.',
    developerSlug: 'buildtech',
    type: 'industry',
    category: 'construction',
    version: '1.3.0',
    color: '#a16207',
    pricingModel: 'subscription',
    priceAmount: 1499,
    billingInterval: 'monthly',
    permissions: ['read:reports', 'read:files', 'access:ai'],
    releaseNotes: 'Added safety compliance checklists.',
    features: ['Milestone tracking', 'Cost variance', 'Subcontractor mgmt', 'Safety compliance', 'Progress photos'],
  },
  // ── Education ──
  {
    slug: 'fee-collector',
    name: 'Fee Collection System',
    tagline: 'Automate school fee collection',
    description: 'Automates school/institute fee collection with reminders, online payments, and receipt generation.',
    developerSlug: 'edutech-india',
    type: 'industry',
    category: 'education',
    version: '1.7.0',
    color: '#6366f1',
    pricingModel: 'subscription',
    priceAmount: 999,
    billingInterval: 'monthly',
    permissions: ['read:crm', 'read:invoices', 'write:invoices', 'read:notifications'],
    releaseNotes: 'Added UPI payment integration.',
    features: ['Fee collection', 'Online payments', 'Auto reminders', 'Receipt generation', 'Defaulter tracking'],
    verified: true,
  },
  // ── Hospitality ──
  {
    slug: 'hotel-booking-sync',
    name: 'Hotel Booking Sync',
    tagline: 'Sync OTAs & direct bookings',
    description: 'Synchronizes hotel bookings from Booking.com, MakeMyTrip, and direct channels with rate management.',
    developerSlug: 'hospitality-os',
    type: 'connector',
    category: 'hospitality',
    version: '1.2.0',
    color: '#d946ef',
    pricingModel: 'subscription',
    priceAmount: 1299,
    billingInterval: 'monthly',
    permissions: ['read:crm', 'write:crm', 'read:invoices', 'access:marketplace'],
    releaseNotes: 'Added Airbnb channel support.',
    features: ['OTA sync', 'Rate management', 'Channel manager', 'Booking dashboard', 'Revenue reports'],
  },
  // ── Legal ──
  {
    slug: 'case-manager',
    name: 'Legal Case Manager',
    tagline: 'Manage cases & billable hours',
    description: 'Manages legal cases, documents, billable hours, and client communications for law firms.',
    developerSlug: 'legaltech',
    type: 'industry',
    category: 'legal',
    version: '1.5.0',
    color: '#a78bfa',
    pricingModel: 'subscription',
    priceAmount: 1799,
    billingInterval: 'monthly',
    permissions: ['read:crm', 'read:files', 'read:invoices', 'read:reports'],
    releaseNotes: 'Added document automation templates.',
    features: ['Case management', 'Billable hours', 'Document automation', 'Deadline tracking', 'Client portal'],
    verified: true,
  },
  // ── Logistics ──
  {
    slug: 'shipment-tracker',
    name: 'Shipment Tracker',
    tagline: 'Track shipments in real-time',
    description: 'Tracks shipments across carriers, provides real-time status updates, and auto-notifies customers.',
    developerSlug: 'logistech',
    type: 'connector',
    category: 'logistics',
    version: '1.4.0',
    color: '#0891b2',
    pricingModel: 'subscription',
    priceAmount: 599,
    billingInterval: 'monthly',
    permissions: ['read:crm', 'read:notifications', 'access:marketplace'],
    releaseNotes: 'Added 20+ carrier integrations.',
    features: ['Multi-carrier tracking', 'Real-time updates', 'Customer alerts', 'Delivery proof', 'Analytics'],
  },
  // ── AI Tools ──
  {
    slug: 'document-classifier',
    name: 'AI Document Classifier',
    tagline: 'Auto-classify any document',
    description: 'Uses AI to classify uploaded documents (invoice, PO, receipt, contract) and extract key fields automatically.',
    developerSlug: 'gstpilot-labs',
    type: 'ai',
    category: 'ai_tools',
    version: '2.0.0',
    color: '#9333ea',
    pricingModel: 'usage_based',
    priceAmount: 2,
    permissions: ['read:files', 'write:files', 'access:ai'],
    releaseNotes: 'Improved accuracy to 96% and added 50+ document types.',
    features: ['Auto classification', 'Field extraction', '50+ doc types', 'Confidence scoring', 'Batch processing'],
    featured: true,
    verified: true,
  },
  {
    slug: 'chatbot-builder',
    name: 'AI Chatbot Builder',
    tagline: 'Build custom AI chatbots',
    description: 'Build and deploy custom AI chatbots trained on your business data. Integrates with Oracle™ for unified responses.',
    developerSlug: 'gstpilot-labs',
    type: 'ai',
    category: 'ai_tools',
    version: '1.8.0',
    color: '#9333ea',
    pricingModel: 'subscription',
    priceAmount: 1999,
    billingInterval: 'monthly',
    permissions: ['access:ai', 'access:oracle', 'read:files', 'read:crm'],
    releaseNotes: 'Added multi-language support and improved training.',
    features: ['No-code builder', 'Custom training', 'Multi-language', 'Oracle integration', 'Analytics'],
    featured: true,
    verified: true,
  },
  // ── Developer Tools ──
  {
    slug: 'api-explorer',
    name: 'API Explorer',
    tagline: 'Explore & test VEYRO APIs',
    description: 'Interactive API explorer with OpenAPI spec, code generation, and live testing for all VEYRO Public APIs.',
    developerSlug: 'gstpilot-labs',
    type: 'api',
    category: 'developer_tools',
    version: '1.0.0',
    color: '#22c55e',
    pricingModel: 'free',
    priceAmount: 0,
    permissions: ['access:marketplace'],
    releaseNotes: 'Initial release with 15+ API modules.',
    features: ['OpenAPI spec', 'Code generation', 'Live testing', 'SDK generation', 'Auth helpers'],
    verified: true,
  },
  {
    slug: 'webhook-tester',
    name: 'Webhook Tester',
    tagline: 'Test webhook deliveries locally',
    description: 'Generates webhook URLs, captures deliveries, and replays events for local development and testing.',
    developerSlug: 'gstpilot-labs',
    type: 'api',
    category: 'developer_tools',
    version: '1.1.0',
    color: '#22c55e',
    pricingModel: 'free',
    priceAmount: 0,
    permissions: ['access:marketplace'],
    releaseNotes: 'Added event replay and inspection.',
    features: ['Webhook URLs', 'Delivery capture', 'Event replay', 'Inspection', 'Export'],
  },
  // ── Analytics ──
  {
    slug: 'custom-dashboards',
    name: 'Custom Dashboards Builder',
    tagline: 'Build dashboards without code',
    description: 'Drag-and-drop dashboard builder with 30+ chart types, real-time data, and sharing capabilities.',
    developerSlug: 'gstpilot-labs',
    type: 'dashboard',
    category: 'analytics',
    version: '2.2.0',
    color: '#0284c7',
    pricingModel: 'subscription',
    priceAmount: 999,
    billingInterval: 'monthly',
    permissions: ['read:reports', 'write:reports', 'read:invoices', 'read:gst'],
    releaseNotes: 'Added real-time streaming charts.',
    features: ['Drag-and-drop', '30+ charts', 'Real-time data', 'Sharing', 'Templates'],
    featured: true,
    verified: true,
  },
  // ── Security ──
  {
    slug: 'access-auditor',
    name: 'Access Auditor',
    tagline: 'Audit user access & permissions',
    description: 'Continuously audits user access, detects anomalies, and generates compliance reports for SOC 2 / ISO 27001.',
    developerSlug: 'secureforge',
    type: 'report',
    category: 'security',
    version: '1.3.0',
    color: '#059669',
    pricingModel: 'enterprise',
    priceAmount: 2499,
    billingInterval: 'monthly',
    permissions: ['manage:audit', 'manage:users', 'read:reports'],
    releaseNotes: 'Added anomaly detection and SOC 2 templates.',
    features: ['Access audit', 'Anomaly detection', 'Compliance reports', 'SOC 2 / ISO 27001', 'Alerts'],
    verified: true,
  },
  // ── Productivity ──
  {
    slug: 'task-automator',
    name: 'Task Automator',
    tagline: 'Automate repetitive tasks',
    description: 'Creates automation rules for repetitive tasks — auto-assign, auto-notify, auto-escalate based on triggers.',
    developerSlug: 'gstpilot-labs',
    type: 'automation',
    category: 'productivity',
    version: '1.9.0',
    color: '#f43f5e',
    pricingModel: 'free',
    priceAmount: 0,
    permissions: ['read:automation', 'write:automation', 'read:notifications', 'write:notifications'],
    releaseNotes: 'Added 20+ trigger templates.',
    features: ['Rule builder', '20+ triggers', 'Auto-assign', 'Auto-notify', 'Escalation rules'],
    verified: true,
  },
];
