// ═══════════════════════════════════════════════════════════════════════════════
// GSTPilot Oracle™ — Workflow Engine: Core Types
// ═══════════════════════════════════════════════════════════════════════════════
//
// Oracle Priority 2 — Autonomous Workflow Engine.
//
// A Workflow is a chain of Action Engine actions executed as ONE end-to-end
// business task. The user says "create an invoice for ABC and email it" and
// Oracle runs: find/create customer → create invoice → email → schedule reminder
// → refresh dashboard → report complete. One workflow, not six chats.
//
// Design principles:
//   • REUSE — every step calls an existing Action Engine action (createInvoice,
//     sendInvoice, scheduleFollowUp, …). Zero duplicated business logic.
//   • PLAN FIRST — the planner builds a WorkflowPlan before execution; the user
//     sees the plan and confirms before any write happens (for risky workflows).
//   • STREAM PROGRESS — the executor emits per-step SSE events so the UI shows
//     live tick-by-tick progress ("Creating invoice… ✓", "Emailing… ✓", …).
//   • FAILURE RECOVERY — if step 4 fails, the executor reports exactly what
//     succeeded and what failed (never a generic "something went wrong"). For
//     critical steps with rollback actions, the executor runs compensating
//     actions to undo partial work (saga pattern).
//   • TRANSACTION SAFETY — where multiple writes must succeed together, the
//     executor supports rollback actions. Prisma cross-action transactions are
//     not feasible (each action calls services with their own writes), so we
//     use compensating actions instead.
//   • PRESERVE THE SaaS — workflows call the SAME shared service layer as the
//     UI. Audit logs, graph events, timeline events, activity logs all fire
//     identically. Oracle and the UI never drift out of sync.
// ═══════════════════════════════════════════════════════════════════════════════

import type { RefreshedContext } from '@/lib/oracle/action-engine/registry';

// ─── Workflow Step ────────────────────────────────────────────────────────────

/**
 * A single step in a workflow. Each step maps 1:1 to an Action Engine action
 * (e.g. createInvoice, sendInvoice, scheduleFollowUp). Steps chain together via
 * template variables in `args` — `{{stepId.data.fieldName}}` is resolved
 * against prior step outputs before execution.
 */
export interface WorkflowStep {
  /** Unique id within the workflow (e.g. 'createInvoice', 'sendInvoice'). */
  id: string;
  /** Action Engine action name (must be a registered action). */
  actionName: string;
  /** Human label shown in the progress UI (e.g. 'Create invoice'). */
  label: string;
  /** One-line description of what this step does and why. */
  description?: string;
  /**
   * Args for the action. May contain template variables resolved against prior
   * step outputs, e.g. `{ id: '{{createInvoice.data.invoiceId}}' }`.
   * Resolution happens just before execution.
   */
  args: Record<string, any>;
  /**
   * Optional skip condition — a template expression that evaluates to a truthy
   * value to skip this step. E.g. `{{createInvoice.data.clientExisted}}` skips
   * a "create customer" step if the customer already existed.
   */
  skipCondition?: string;
  /**
   * Whether this step is critical. If a critical step fails, the entire
   * workflow halts and rollback runs for prior steps. If a non-critical step
   * fails, the workflow continues and reports partial success.
   * Default: true for steps that create/modify data; false for side-effects.
   */
  critical?: boolean;
  /**
   * Optional compensating rollback action. If this step (or a later critical
   * step) fails, the executor calls this action to undo the work.
   * E.g. a createInvoice step might roll back via deleteInvoice.
   */
  rollback?: {
    actionName: string;
    /** Args (also templated) for the rollback action. */
    args: Record<string, any>;
  };
}

// ─── Workflow Plan ────────────────────────────────────────────────────────────

export type WorkflowCategory = 'sales' | 'payment' | 'gst' | 'crm' | 'reports' | 'operations' | 'banking' | 'custom';

export type WorkflowRiskLevel = 'low' | 'medium' | 'high';

/**
 * A complete workflow plan — the ordered steps + metadata. Built by the planner
 * (template match or LLM) and shown to the user for confirmation before
 * execution.
 */
export interface WorkflowPlan {
  /** Unique workflow id (generated by the planner). */
  id: string;
  /** Which template spawned this plan (e.g. 'sales.invoiceAndEmail'), if any. */
  templateId?: string;
  /** Human title (e.g. 'Create invoice for ABC Pvt Ltd and email it'). */
  title: string;
  /** One-line description for the confirm card. */
  description: string;
  /** Workflow category — drives the icon + color in the UI. */
  category: WorkflowCategory;
  /** Ordered list of steps. */
  steps: WorkflowStep[];
  /** Risk level — drives whether confirmation is required. */
  riskLevel: WorkflowRiskLevel;
  /**
   * Whether the user must confirm before execution. High-risk workflows
   * (delete, GST file, bulk, external sends) always require confirmation.
   * Low-risk read-only workflows may skip confirmation.
   */
  requiresConfirmation: boolean;
  /** Estimated total duration in seconds (for the UI). */
  estimatedSeconds: number;
  /** The originating user message that spawned this plan. */
  sourceMessage: string;
  /** ISO timestamp of plan creation. */
  createdAt: string;
}

// ─── Execution Status ─────────────────────────────────────────────────────────

export type WorkflowStepStatus =
  | 'pending'    // not yet started
  | 'running'    // currently executing
  | 'success'    // completed successfully
  | 'skipped'    // skipped due to skipCondition
  | 'failed'     // failed (error captured)
  | 'rolled-back'; // was successful but rolled back due to a later critical failure

/** Per-step result captured during execution. */
export interface WorkflowStepResult {
  stepId: string;
  actionName: string;
  label: string;
  status: WorkflowStepStatus;
  /** Human summary from the action's ActionResult.summary. */
  summary?: string;
  /** Action result data — used to resolve template vars in subsequent steps. */
  data?: Record<string, any>;
  /** Error message if status === 'failed'. */
  error?: string;
  startedAt?: string;
  completedAt?: string;
  durationMs?: number;
}

export type WorkflowOverallStatus = 'success' | 'partial' | 'failed' | 'cancelled';

/** The final result of a workflow execution. */
export interface WorkflowResult {
  /** True only if ALL critical steps succeeded (non-critical may have failed). */
  ok: boolean;
  /** Overall status — 'success' = all steps ok; 'partial' = some non-critical failed; 'failed' = a critical step failed. */
  status: WorkflowOverallStatus;
  /** Per-step results in execution order. */
  steps: WorkflowStepResult[];
  /** Human-readable overall summary (what succeeded, what failed). */
  summary: string;
  /** The final refreshed dashboard context (snapshot + recent data). */
  refreshedContext?: RefreshedContext;
  /** Counters for the UI. */
  completedCount: number;
  failedCount: number;
  skippedCount: number;
  /** Total execution duration. */
  durationMs: number;
  /** Deep-links to the most relevant module page(s). */
  viewIn?: Array<{ label: string; href: string }>;
}

// ─── SSE Event payloads (emitted by the execute endpoint) ─────────────────────

export type WorkflowStreamEvent =
  | { type: 'workflow-start'; plan: { id: string; title: string; category: WorkflowCategory; stepCount: number } }
  | { type: 'workflow-step-start'; stepId: string; label: string; actionName: string; index: number; total: number }
  | { type: 'workflow-step-success'; stepId: string; label: string; summary: string; data?: Record<string, any>; durationMs: number }
  | { type: 'workflow-step-skipped'; stepId: string; label: string; reason: string }
  | { type: 'workflow-step-failed'; stepId: string; label: string; error: string; critical: boolean; willRollback: boolean }
  | { type: 'workflow-rollback-start'; stepId: string; actionName: string }
  | { type: 'workflow-rollback-done'; stepId: string; ok: boolean; summary?: string }
  | { type: 'workflow-complete'; result: WorkflowResult };

// ─── Planner input ────────────────────────────────────────────────────────────

/** The raw input to the planner — user message + extracted args from the LLM. */
export interface WorkflowPlannerInput {
  /** The user's natural-language message. */
  message: string;
  /** The org id (tenant scope). */
  orgId: string;
  /** Optional structured args the LLM extracted (e.g. { customerName, amount }). */
  extractedArgs?: Record<string, any>;
  /** The session id (for persistence). */
  sessionId?: string;
  /** The user id. */
  userId?: string;
}
