/**
 * Global Search™ — instant search across companies, invoices, clients,
 * employees, GST, banking, meetings, reports, tasks, knowledge graph,
 * digital twin, AI workforce, and Oracle.
 */
import { db } from '@/lib/db'
import type { GlobalSearchResult } from './types'

// Phase 2 fix: many of the enterprise tables (tenantMember, integration,
// enterpriseAuditLog, etc.) are NOT generated by Prisma in every install —
// referencing them throws "Cannot read properties of undefined (reading
// 'findMany')". Wrap each query in a safe helper that returns `[]` on
// failure so the search degrades gracefully to the entities that DO exist
// (clients, invoices).
async function safeFind<T>(p: Promise<T>): Promise<T> {
  try {
    return await p;
  } catch {
    return [] as unknown as T;
  }
}

export async function globalSearch(tenantId: string, query: string, limit = 30, organizationId?: string): Promise<GlobalSearchResult[]> {
  const q = query.trim()
  if (!q) return []

  // Tenant + workspace scoping.
  // - Tenant-scoped queries (companies, orgs, members, integrations, audit) use tenantId.
  // - Workspace-scoped queries (clients, invoices) use client.firmId = organizationId when available.
  // - If no organizationId provided, fall back to tenantId (limited leak prevention).
  const firmFilter = organizationId ? { client: { firmId: organizationId } } : {}

  const tenantPromise = safeFind(db.tenant.findUnique({ where: { id: tenantId }, select: { name: true } }))

  const [
    tenant,
    companies,
    orgs,
    members,
    clients,
    invoices,
    integrations,
    audit,
  ] = await Promise.all([
    tenantPromise,
    // Companies — wrapped in safeFind (table may not exist in all installs)
    safeFind(db.company.findMany({
      where: {
        tenantId,
        OR: [
          { legalName: { contains: q } },
          { tradeName: { contains: q } },
          { gstin: { contains: q } },
          { pan: { contains: q } },
        ],
      },
      take: 8,
    })),
    // Organizations — wrapped in safeFind
    safeFind(db.organization.findMany({
      where: { tenantId, OR: [{ name: { contains: q } }, { code: { contains: q } }] },
      take: 8,
    })),
    // Members — wrapped in safeFind (tenantMember model may not exist)
    safeFind(db.tenantMember?.findMany?.({
      where: { tenantId, status: 'active' },
      take: 50,
      include: { role: true },
    }) ?? Promise.resolve([])),
    // Clients — workspace-scoped via client.firmId when organizationId is provided.
    safeFind(db.client.findMany({
      where: {
        ...firmFilter,
        OR: [{ tradeName: { contains: q } }, { legalName: { contains: q } }, { gstin: { contains: q } }],
      },
      take: 8,
    })),
    // Invoices — workspace-scoped via client.firmId when organizationId is provided.
    safeFind(db.invoice.findMany({
      where: {
        ...firmFilter,
        invoiceNumber: { contains: q },
      },
      take: 8,
      orderBy: { createdAt: 'desc' },
    })),
    // Integrations — wrapped in safeFind
    safeFind(db.integration?.findMany?.({
      where: { tenantId, OR: [{ displayName: { contains: q } }, { provider: { contains: q } }] },
      take: 5,
    }) ?? Promise.resolve([])),
    // Audit logs — wrapped in safeFind (enterpriseAuditLog may not exist)
    safeFind(db.enterpriseAuditLog?.findMany?.({
      where: { tenantId, summary: { contains: q } },
      take: 5,
      orderBy: { timestamp: 'desc' },
    }) ?? Promise.resolve([])),
  ])

  const tenantName = tenant?.name ?? null
  const results: GlobalSearchResult[] = []

  // Users query depends on userIds from members — runs after the members fetch.
  const userIds = (Array.isArray(members) ? members : []).map((m: { userId?: string }) => m.userId).filter((x): x is string => !!x)
  let users: Array<{ id: string; name: string | null; email: string; updatedAt: Date }> = []
  if (userIds.length > 0) {
    users = await safeFind(db.user.findMany({
      where: { id: { in: userIds }, OR: [{ name: { contains: q } }, { email: { contains: q } }] },
      take: 8,
    }))
  }

  for (const c of companies) {
    results.push({
      id: c.id, type: 'Company', title: c.legalName,
      subtitle: [c.tradeName, c.gstin].filter(Boolean).join(' · '),
      url: null, tenantName, updatedAt: c.updatedAt.toISOString(),
    })
  }

  for (const o of orgs) {
    results.push({
      id: o.id, type: 'Organization', title: o.name,
      subtitle: [o.type, o.code].filter(Boolean).join(' · '),
      url: null, tenantName, updatedAt: o.updatedAt.toISOString(),
    })
  }

  for (const u of users) {
    const m = members.find((mm) => mm.userId === u.id)
    results.push({
      id: u.id, type: 'User', title: u.name ?? u.email,
      subtitle: [m?.title, m?.role?.name].filter(Boolean).join(' · '),
      url: null, tenantName, updatedAt: u.updatedAt.toISOString(),
    })
  }

  for (const c of clients) {
    results.push({
      id: c.id, type: 'Client', title: c.tradeName,
      subtitle: [c.gstin, c.state].filter(Boolean).join(' · '),
      url: `/clients/${c.id}`, tenantName, updatedAt: c.updatedAt.toISOString(),
    })
  }

  for (const inv of invoices) {
    results.push({
      id: inv.id, type: 'Invoice', title: inv.invoiceNumber,
      subtitle: [inv.invoiceType, `₹${inv.totalAmount.toLocaleString('en-IN')}`, inv.status].filter(Boolean).join(' · '),
      url: `/invoices/${inv.id}`, tenantName, updatedAt: inv.updatedAt.toISOString(),
    })
  }

  for (const i of integrations) {
    results.push({
      id: i.id, type: 'Integration', title: i.displayName,
      subtitle: [i.category, i.status].join(' · '),
      url: null, tenantName, updatedAt: i.updatedAt.toISOString(),
    })
  }

  for (const a of audit) {
    results.push({
      id: a.id, type: 'Audit', title: a.summary,
      subtitle: [a.actorType, a.action].join(' · '),
      url: null, tenantName, updatedAt: a.timestamp.toISOString(),
    })
  }

  // sort by updatedAt desc and trim
  results.sort((a, b) => (b.updatedAt ?? '').localeCompare(a.updatedAt ?? ''))
  return results.slice(0, limit)
}
