// ═══════════════════════════════════════════════════════════════════════════════
// GSTPilot — Centralized Business Timeline Emitter (SERVER-ONLY)
// ═══════════════════════════════════════════════════════════════════════════════
//
// Single entry point for emitting "Business Timeline" events. Every important
// CRUD action in the platform — customer created, invoice issued, payment
// received, GST return filed, Zoho sync completed, Google connected, Oracle
// activated, expense recorded, invoice overdue, settings updated — calls
// `emitTimelineEvent(...)` so the event lands in the canonical
// `BusinessEvent` Prisma table and surfaces on the dashboard Timeline widget.
//
// DESIGN CONTRACT (read before changing this file):
//   1. The Prisma `BusinessEvent` model only has a fixed set of columns
//      (id, businessId, type, source, payload, severity, status, createdAt).
//      Anything that does not map directly (title, description, actor,
//      metadata) is serialized into the `payload` JSON column.
//   2. `businessId` carries the organizationId (the same identifier used as
//      `firmId` everywhere else — there is currently no firmId↔organizationId
//      bridge, the orgId IS the firmId).
//   3. Every emit call is FIRE-AND-FORGET SAFE. If the DB is unreachable, the
//      table is missing, or any other error occurs, the call logs a warning
//      and returns. It NEVER throws to the caller — the parent operation
//      (invoice creation, payment recording, etc.) MUST still succeed.
//   4. `local-` org IDs (guest/demo workspaces) never hit Prisma — the emit
//      call is silently skipped (no Prisma row would ever be readable back
//      anyway, since listTimelineEvents also short-circuits for local- orgs).
//   5. The id is generated by Prisma's `@default(cuid())` (we omit `id` from
//      the create payload so Prisma assigns a real cuid server-side).
//
// USAGE:
//   import { emitTimelineEvent } from '@/lib/timeline/emit';
//   try {
//     await emitTimelineEvent({
//       organizationId,
//       type: 'invoice.created',
//       title: `Invoice ${inv.invoiceNumber} created`,
//       description: `₹${inv.totalAmount} invoice issued for ${customerName}.`,
//       actor: { userId, userName },
//       metadata: { invoiceNumber, amount, customerId },
//       severity: 'info',
//     });
//   } catch { /* already swallowed inside emit — never reaches here */ }
// ═══════════════════════════════════════════════════════════════════════════════

import { db } from '@/lib/db';

// ─── Types ────────────────────────────────────────────────────────────────────

/** Canonical timeline event types (extensible — new types added as flows grow). */
export type TimelineEventType =
  | 'customer.created'
  | 'invoice.created'
  | 'invoice.paid'
  | 'invoice.overdue'
  | 'zoho.sync.completed'
  | 'google.connected'
  | 'oracle.activated'
  | 'return.created'
  | 'settings.updated'
  | 'expense.created'
  | 'payment.received'
  | 'bank.connected';

/** Severity buckets the UI uses to color the timeline dot. */
export type TimelineSeverity = 'info' | 'success' | 'warning' | 'critical';

/** The actor who triggered the event (best-effort — may be system). */
export interface TimelineActor {
  userId?: string;
  userName?: string;
}

/** Params for emitTimelineEvent — see file header for the full contract. */
export interface EmitTimelineEventParams {
  organizationId: string;
  type: TimelineEventType | string;
  title: string;
  description?: string;
  actor?: TimelineActor;
  metadata?: Record<string, unknown>;
  severity?: TimelineSeverity;
}

/** Internal payload shape stored as JSON in the BusinessEvent.payload column. */
interface BusinessEventPayload {
  title: string;
  description?: string;
  actor?: TimelineActor;
  metadata?: Record<string, unknown>;
}

/**
 * The normalized timeline event shape returned by `listTimelineEvents`.
 * This is the shape the dashboard UI consumes — `id`, `type`, `title`,
 * `description`, `severity`, `createdAt`, plus the raw payload + metadata
 * for richer rendering.
 */
export interface TimelineEvent {
  id: string;
  organizationId: string;
  type: string;
  source: string;
  severity: string;
  status: string;
  title: string;
  description?: string;
  actor?: TimelineActor;
  metadata?: Record<string, unknown>;
  createdAt: string; // ISO string
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

/**
 * Returns true for local (guest/demo) org IDs that have no Prisma backing.
 * The dashboard creates a "local-<uid>" workspace when Firebase is unreachable
 * or for guest users — these never have BusinessEvent rows, so we skip both
 * the write AND the read path for them.
 */
export function isLocalOrgId(organizationId: string | null | undefined): boolean {
  return Boolean(organizationId) && String(organizationId).startsWith('local-');
}

/**
 * Map our app-level severity buckets to the BusinessEvent.severity column
 * value. The Prisma schema documents severity as
 * "info | low | medium | high | critical", but it is a free-form String — we
 * write our own bucket names so the UI can color dots consistently without
 * a translation layer.
 */
function normalizeSeverity(sev: TimelineSeverity | undefined): string {
  switch (sev) {
    case 'info':
    case 'success':
    case 'warning':
    case 'critical':
      return sev;
    default:
      return 'info';
  }
}

/**
 * Best-effort source derivation from the event type. The first dotted segment
 * of the type ("customer", "invoice", "zoho", "google", "oracle", "return",
 * "settings", "expense", "payment", "bank") becomes the source. Falls back to
 * "system" for unknown types.
 */
function deriveSource(type: string): string {
  const head = String(type).split('.')[0];
  if (!head) return 'system';
  const known = new Set([
    'customer',
    'invoice',
    'zoho',
    'google',
    'oracle',
    'return',
    'settings',
    'expense',
    'payment',
    'bank',
  ]);
  return known.has(head) ? head : 'system';
}

// ─── Public API ───────────────────────────────────────────────────────────────

/**
 * Emit a single Business Timeline event. FIRE-AND-FORGET SAFE — never throws
 * to the caller. See file header for the full contract.
 *
 * @returns Promise<void> — always resolves (never rejects) even on DB errors.
 */
export async function emitTimelineEvent(
  params: EmitTimelineEventParams,
): Promise<void> {
  try {
    // Validate the bare minimum — if there's no org or no type, there's
    // nothing to record. Silent skip (do NOT throw — the caller's primary
    // operation must not be impacted).
    if (!params?.organizationId || !params?.type || !params?.title) {
      return;
    }

    // Local (guest/demo) org IDs never hit Prisma — there is no Firm row to
    // scope events to, and listTimelineEvents also short-circuits for these.
    if (isLocalOrgId(params.organizationId)) {
      return;
    }

    const payload: BusinessEventPayload = {
      title: params.title,
      description: params.description,
      actor: params.actor,
      metadata: params.metadata,
    };

    // Prisma assigns the cuid via `@default(cuid())` because we omit `id`
    // from the data object. createdAt is also defaulted by the schema.
    await db.businessEvent.create({
      data: {
        businessId: params.organizationId,
        type: params.type,
        source: deriveSource(params.type),
        severity: normalizeSeverity(params.severity),
        status: 'open',
        payload: JSON.stringify(payload),
      },
    });
  } catch (err) {
    // NEVER break the parent operation. Log and swallow.
    console.warn(
      '[timeline] emitTimelineEvent failed (type=%s, org=%s):',
      params?.type,
      params?.organizationId,
      err instanceof Error ? err.message : err,
    );
  }
}

/**
 * Read the most recent Business Timeline events for an organization, newest
 * first. Returns an empty array for local- org IDs (no Prisma backing) or
 * if the table is missing/unreadable.
 *
 * @param organizationId The org/firm id (e.g. "preview-org" or a real org id)
 * @param limit Max events to return (default 50, capped at 200)
 */
export async function listTimelineEvents(
  organizationId: string,
  limit: number = 50,
): Promise<TimelineEvent[]> {
  try {
    if (!organizationId) return [];
    if (isLocalOrgId(organizationId)) return [];

    const safeLimit = Math.max(1, Math.min(200, Math.floor(limit) || 50));

    const rows = await db.businessEvent.findMany({
      where: { businessId: organizationId },
      orderBy: { createdAt: 'desc' },
      take: safeLimit,
    });

    return rows.map(parseBusinessEventRow).filter(Boolean) as TimelineEvent[];
  } catch (err) {
    console.warn(
      '[timeline] listTimelineEvents failed (org=%s):',
      organizationId,
      err instanceof Error ? err.message : err,
    );
    return [];
  }
}

// ─── Internal: row → TimelineEvent mapping ────────────────────────────────────

/**
 * Parse a raw BusinessEvent Prisma row into the TimelineEvent shape consumed
 * by the dashboard. The payload JSON string is deserialized into title,
 * description, actor, and metadata. If the payload is missing or malformed,
 * we synthesize a minimal title from the type so the row is never invisible.
 */
function parseBusinessEventRow(row: {
  id: string;
  businessId: string | null;
  type: string;
  source: string;
  payload: string | null;
  severity: string;
  status: string;
  createdAt: Date;
}): TimelineEvent {
  let payload: BusinessEventPayload | null = null;
  if (row.payload) {
    try {
      payload = JSON.parse(row.payload) as BusinessEventPayload;
    } catch {
      payload = null;
    }
  }

  return {
    id: row.id,
    organizationId: row.businessId ?? '',
    type: row.type,
    source: row.source,
    severity: row.severity,
    status: row.status,
    title: payload?.title ?? prettifyType(row.type),
    description: payload?.description,
    actor: payload?.actor,
    metadata: payload?.metadata,
    createdAt: row.createdAt.toISOString(),
  };
}

/** Convert "invoice.created" → "Invoice created" for fallback titles. */
function prettifyType(type: string): string {
  return String(type)
    .split(/[._]/)
    .filter(Boolean)
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join(' ');
}
