// ═══════════════════════════════════════════════════════════════════════════════
// GSTPilot Oracle CFO™ — GST Report Exporter (PDF / Excel / CSV)
//
// Generates downloadable GST report files from a structured GSTReport.
//
// Three formats:
//   • PDF  — professional multi-section report (uses pdfkit, matches invoice-pdf style)
//   • Excel — multi-sheet workbook (uses xlsx/SheetJS)
//   • CSV  — flat CSV with all key metrics
//
// All three are pure-data exports — no fake values, every number comes from
// the GSTReport passed in. The /export API route picks the format and streams
// the buffer back.
// ═══════════════════════════════════════════════════════════════════════════════

import type { GSTReport } from './gst-report-engine';

// ─── Colors (matching invoice-pdf.ts for visual consistency) ──────────────

const EMERALD = '#10b981';
const DARK = '#0a0a0a';
const GRAY = '#666666';
const LIGHT_GRAY = '#e5e5e5';
const BG_LIGHT = '#f9fafb';
const AMBER = '#f59e0b';
const ROSE = '#ef4444';

// ═══════════════════════════════════════════════════════════════════════════════
// PDF EXPORT
// ═══════════════════════════════════════════════════════════════════════════════

export async function generateGSTReportPDF(report: GSTReport): Promise<{ buffer: Buffer; base64: string }> {
  const PDFDocument = (await import('pdfkit')).default;
  const doc = new PDFDocument({ size: 'A4', margin: 50 });
  const chunks: Buffer[] = [];
  doc.on('data', (chunk: Buffer) => chunks.push(chunk));
  const pdfPromise = new Promise<Buffer>((resolve) => {
    doc.on('end', () => resolve(Buffer.concat(chunks)));
  });

  const W = 595; // A4 width in points
  const M = 50;
  const CW = W - M * 2;

  // ═══ HEADER ═══
  doc.save();
  doc.rect(0, 0, W, 6).fill(EMERALD);
  doc.restore();

  doc.save();
  doc.roundedRect(M, 30, 44, 44, 10).fill(EMERALD);
  doc.fillColor('#ffffff').fontSize(26).font('Helvetica-Bold');
  doc.text('G', M + 14, 38);
  doc.restore();

  doc.fillColor(DARK).fontSize(22).font('Helvetica-Bold');
  doc.text('GSTPilot', M + 56, 32);

  doc.fillColor(GRAY).fontSize(9).font('Helvetica');
  doc.text('GST Report — Generated by Oracle CFO™', M + 56, 58);

  doc.fontSize(10).font('Helvetica-Bold');
  doc.text(report.intent.reportType.toUpperCase(), W - M - 100, 30, { width: 100, align: 'right' });
  doc.font('Helvetica').fillColor(GRAY).fontSize(9);
  doc.text(report.intent.periodLabel, W - M - 100, 46, { width: 100, align: 'right' });
  doc.text(`Generated ${new Date(report.generatedAt).toLocaleDateString('en-IN')}`, W - M - 100, 60, { width: 100, align: 'right' });

  doc.save();
  doc.moveTo(M, 90).lineTo(W - M, 90).strokeColor(LIGHT_GRAY).lineWidth(1).stroke();
  doc.restore();

  // ═══ SELLER / ORG DETAILS ═══
  let y = 105;
  doc.fillColor(DARK).fontSize(11).font('Helvetica-Bold');
  doc.text(report.dataSummary ? 'Organization Details' : '', M, y);
  y += 16;
  doc.font('Helvetica').fillColor(GRAY).fontSize(9);
  if (report.intent.branch) {
    doc.text(`Branch: ${report.intent.branch}`, M, y); y += 12;
  }
  doc.text(`Report ID: ${report.reportId}`, M, y); y += 12;
  doc.text(`Period: ${report.intent.startDate} → ${report.intent.endDate}`, M, y); y += 18;

  // ═══ EXECUTIVE SUMMARY (KPI cards) ═══
  doc.fillColor(DARK).fontSize(13).font('Helvetica-Bold');
  doc.text('Executive Summary', M, y);
  y += 20;

  const calc = report.calculations;
  const kpis = [
    { label: 'Taxable Turnover', value: `₹${calc.totalTaxableTurnover.toLocaleString('en-IN')}` },
    { label: 'Total Output Tax', value: `₹${calc.totalOutputTax.toLocaleString('en-IN')}` },
    { label: 'ITC Available', value: `₹${calc.itcAvailable.toLocaleString('en-IN')}` },
    { label: 'Net GST Payable', value: `₹${calc.netPayable.toLocaleString('en-IN')}`, highlight: true },
    { label: 'Exempt Supplies', value: `₹${calc.totalExempt.toLocaleString('en-IN')}` },
    { label: 'Zero-Rated (Export)', value: `₹${(calc.totalZeroRated + calc.totalExport).toLocaleString('en-IN')}` },
  ];

  const cardW = (CW - 20) / 3;
  const cardH = 50;
  for (let i = 0; i < kpis.length; i++) {
    const kpi = kpis[i];
    const col = i % 3;
    const row = Math.floor(i / 3);
    const x = M + col * (cardW + 10);
    const cy = y + row * (cardH + 10);
    doc.save();
    doc.roundedRect(x, cy, cardW, cardH, 6).fillAndStroke(kpi.highlight ? EMERALD : BG_LIGHT, kpi.highlight ? EMERALD : LIGHT_GRAY);
    doc.fillColor(kpi.highlight ? '#ffffff' : GRAY).fontSize(8).font('Helvetica');
    doc.text(kpi.label.toUpperCase(), x + 8, cy + 8, { width: cardW - 16 });
    doc.fillColor(kpi.highlight ? '#ffffff' : DARK).fontSize(13).font('Helvetica-Bold');
    doc.text(kpi.value, x + 8, cy + 22, { width: cardW - 16 });
    doc.restore();
  }
  y += Math.ceil(kpis.length / 3) * (cardH + 10) + 10;

  // ═══ SALES SUMMARY (by slab) ═══
  y = drawSectionHeader(doc, 'Sales Summary (Outward Supplies)', M, y, W);
  const salesRows: Array<{ cols: string[]; bold?: boolean }> = [
    { cols: ['Slab', 'Invoices', 'Taxable', 'CGST', 'SGST', 'IGST', 'Total Tax'], bold: true },
    ...calc.salesBySlab.map((s) => ({
      cols: [
        `${s.gstRate}%`,
        String(s.invoiceCount),
        `₹${s.taxableValue.toLocaleString('en-IN')}`,
        `₹${s.cgst.toLocaleString('en-IN')}`,
        `₹${s.sgst.toLocaleString('en-IN')}`,
        `₹${s.igst.toLocaleString('en-IN')}`,
        `₹${s.totalTax.toLocaleString('en-IN')}`,
      ],
    })),
    {
      cols: [
        'TOTAL',
        String(calc.salesBySlab.reduce((s, r) => s + r.invoiceCount, 0)),
        `₹${calc.totalTaxableTurnover.toLocaleString('en-IN')}`,
        `₹${calc.outputCGST.toLocaleString('en-IN')}`,
        `₹${calc.outputSGST.toLocaleString('en-IN')}`,
        `₹${calc.outputIGST.toLocaleString('en-IN')}`,
        `₹${calc.totalOutputTax.toLocaleString('en-IN')}`,
      ],
      bold: true,
    },
  ];
  y = drawTable(doc, salesRows, [60, 60, 95, 80, 80, 80, 90], M, y, W);

  // ═══ PURCHASE SUMMARY (by slab) ═══
  y = ensureSpace(doc, y, 120);
  y = drawSectionHeader(doc, 'Purchase Summary (Inward Supplies / ITC)', M, y, W);
  const purchaseRows: Array<{ cols: string[]; bold?: boolean }> = [
    { cols: ['Slab', 'Invoices', 'Taxable', 'CGST', 'SGST', 'IGST', 'ITC'], bold: true },
    ...calc.purchasesBySlab.map((s) => ({
      cols: [
        `${s.gstRate}%`,
        String(s.invoiceCount),
        `₹${s.taxableValue.toLocaleString('en-IN')}`,
        `₹${s.cgst.toLocaleString('en-IN')}`,
        `₹${s.sgst.toLocaleString('en-IN')}`,
        `₹${s.igst.toLocaleString('en-IN')}`,
        `₹${s.totalTax.toLocaleString('en-IN')}`,
      ],
    })),
    {
      cols: [
        'TOTAL',
        String(calc.purchasesBySlab.reduce((s, r) => s + r.invoiceCount, 0)),
        `₹${calc.purchasesBySlab.reduce((s, r) => s + r.taxableValue, 0).toLocaleString('en-IN')}`,
        `₹${calc.itcCGST.toLocaleString('en-IN')}`,
        `₹${calc.itcSGST.toLocaleString('en-IN')}`,
        `₹${calc.itcIGST.toLocaleString('en-IN')}`,
        `₹${calc.itcAvailable.toLocaleString('en-IN')}`,
      ],
      bold: true,
    },
  ];
  y = drawTable(doc, purchaseRows, [60, 60, 95, 80, 80, 80, 90], M, y, W);

  // ═══ GST LIABILITY BREAKDOWN ═══
  y = ensureSpace(doc, y, 200);
  y = drawSectionHeader(doc, 'GST Liability Breakdown', M, y, W);
  const liabilityRows: Array<{ cols: string[]; bold?: boolean; highlight?: boolean }> = [
    { cols: ['Output CGST', `₹${calc.outputCGST.toLocaleString('en-IN')}`] },
    { cols: ['Output SGST', `₹${calc.outputSGST.toLocaleString('en-IN')}`] },
    { cols: ['Output IGST', `₹${calc.outputIGST.toLocaleString('en-IN')}`] },
    { cols: ['Output Cess', `₹${calc.outputCess.toLocaleString('en-IN')}`] },
    { cols: ['Total Output Tax', `₹${calc.totalOutputTax.toLocaleString('en-IN')}`], bold: true },
    { cols: ['Less: ITC Utilized', `−₹${calc.itcUtilized.toLocaleString('en-IN')}`] },
    { cols: ['Net CGST Payable', `₹${calc.netCGSTPayable.toLocaleString('en-IN')}`] },
    { cols: ['Net SGST Payable', `₹${calc.netSGSTPayable.toLocaleString('en-IN')}`] },
    { cols: ['Net IGST Payable', `₹${calc.netIGSTPayable.toLocaleString('en-IN')}`] },
    { cols: ['Net Cess Payable', `₹${calc.netCessPayable.toLocaleString('en-IN')}`] },
    { cols: ['Net GST Payable', `₹${calc.netPayable.toLocaleString('en-IN')}`], bold: true, highlight: true },
  ];
  y = drawKeyValueTable(doc, liabilityRows, M, y, W);

  // ═══ ITC SUMMARY ═══
  y = ensureSpace(doc, y, 150);
  y = drawSectionHeader(doc, 'ITC Summary', M, y, W);
  const itcRows: Array<{ cols: string[]; bold?: boolean }> = [
    { cols: ['ITC Available (CGST)', `₹${calc.itcCGST.toLocaleString('en-IN')}`] },
    { cols: ['ITC Available (SGST)', `₹${calc.itcSGST.toLocaleString('en-IN')}`] },
    { cols: ['ITC Available (IGST)', `₹${calc.itcIGST.toLocaleString('en-IN')}`] },
    { cols: ['ITC Available (Cess)', `₹${calc.itcCess.toLocaleString('en-IN')}`] },
    { cols: ['Total ITC Available', `₹${calc.itcAvailable.toLocaleString('en-IN')}`], bold: true },
    { cols: ['ITC Reversed (Rule 42/43)', `−₹${calc.itcReversed.toLocaleString('en-IN')}`] },
    { cols: ['ITC Utilized', `₹${calc.itcUtilized.toLocaleString('en-IN')}`] },
    { cols: ['Refund Eligible', `₹${calc.refundEligible.toLocaleString('en-IN')}`] },
  ];
  y = drawKeyValueTable(doc, itcRows, M, y, W);

  // ═══ TOP CUSTOMERS ═══
  y = ensureSpace(doc, y, 100);
  y = drawSectionHeader(doc, 'Top Customers (by tax contribution)', M, y, W);
  const customerRows: Array<{ cols: string[]; bold?: boolean }> = [
    { cols: ['Customer', 'Invoices', 'Taxable', 'Tax'], bold: true },
    ...report.topCustomers.slice(0, 10).map((c) => ({
      cols: [
        c.name + (c.gstin ? ` (${c.gstin})` : ''),
        String(c.invoiceCount),
        `₹${c.taxableValue.toLocaleString('en-IN')}`,
        `₹${c.taxAmount.toLocaleString('en-IN')}`,
      ],
    })),
  ];
  y = drawTable(doc, customerRows, [200, 70, 130, 130], M, y, W);

  // ═══ TOP VENDORS ═══
  y = ensureSpace(doc, y, 100);
  y = drawSectionHeader(doc, 'Top Vendors (by ITC contribution)', M, y, W);
  const vendorRows: Array<{ cols: string[]; bold?: boolean }> = [
    { cols: ['Vendor', 'Invoices', 'Taxable', 'ITC'], bold: true },
    ...report.topVendors.slice(0, 10).map((v) => ({
      cols: [
        v.name + (v.gstin ? ` (${v.gstin})` : ''),
        String(v.invoiceCount),
        `₹${v.taxableValue.toLocaleString('en-IN')}`,
        `₹${v.taxAmount.toLocaleString('en-IN')}`,
      ],
    })),
  ];
  y = drawTable(doc, vendorRows, [200, 70, 130, 130], M, y, W);

  // ═══ VALIDATION REPORT ═══
  y = ensureSpace(doc, y, 100);
  y = drawSectionHeader(doc, `Validation Report (${report.validation.criticalCount} critical, ${report.validation.warningCount} warnings, ${report.validation.infoCount} info)`, M, y, W);
  const val = report.validation;
  const valSummary: Array<{ cols: string[]; bold?: boolean }> = [
    { cols: ['Invoices checked', String(val.totalChecked)] },
    { cols: ['Passed validation', String(val.passed)] },
    { cols: ['Critical issues', String(val.criticalCount)], bold: val.criticalCount > 0 },
    { cols: ['Warnings', String(val.warningCount)] },
    { cols: ['Info (RCM, exempt, etc.)', String(val.infoCount)] },
    { cols: ['Duplicate invoice numbers', String(val.duplicateInvoiceNumbers.length)] },
    { cols: ['Invalid GSTINs', String(val.invalidGstins.length)] },
    { cols: ['Future-dated invoices', String(val.futureDatedInvoices.length)] },
    { cols: ['Reverse-charge invoices', String(val.reverseChargeInvoices.length)] },
    { cols: ['Exempt / nil-rated invoices', String(val.exemptInvoices.length)] },
    { cols: ['Zero-rated invoices', String(val.zeroRatedInvoices.length)] },
    { cols: ['Export invoices', String(val.exportInvoices.length)] },
  ];
  y = drawKeyValueTable(doc, valSummary, M, y, W);

  // Top 10 critical issues (if any)
  if (val.criticalCount > 0) {
    y = ensureSpace(doc, y, 80);
    doc.fillColor(ROSE).fontSize(10).font('Helvetica-Bold');
    doc.text('Top Critical Issues', M, y);
    y += 14;
    doc.font('Helvetica').fillColor(GRAY).fontSize(8);
    for (const issue of val.issues.filter((i) => i.severity === 'critical').slice(0, 10)) {
      y = ensureSpace(doc, y, 30);
      doc.fillColor(DARK).font('Helvetica-Bold').fontSize(8);
      doc.text(`${issue.invoiceNumber} [${issue.field}]`, M, y);
      y += 10;
      doc.fillColor(GRAY).font('Helvetica').fontSize(8);
      doc.text(issue.message, M + 10, y, { width: CW - 20 });
      y += 16;
    }
  }

  // ═══ CROSS-CHECKS ═══
  y = ensureSpace(doc, y, 80);
  y = drawSectionHeader(doc, 'Cross-Checks', M, y, W);
  const checkRows: Array<{ cols: string[]; bold?: boolean }> = [
    { cols: ['Check', 'Expected', 'Actual', 'Status'], bold: true },
    ...calc.crossChecks.map((c) => ({
      cols: [c.label, c.expected, c.actual, c.match ? '✓ Pass' : '✗ Fail'],
    })),
  ];
  y = drawTable(doc, checkRows, [180, 110, 110, 80], M, y, W);

  // ═══ MONTHLY COMPARISON ═══
  y = ensureSpace(doc, y, 100);
  y = drawSectionHeader(doc, 'Monthly Comparison (last 6 periods)', M, y, W);
  const monthlyRows: Array<{ cols: string[]; bold?: boolean }> = [
    { cols: ['Period', 'Taxable', 'Output Tax', 'ITC', 'Net Payable'], bold: true },
    ...report.monthlyComparison.map((m) => ({
      cols: [
        m.periodLabel,
        `₹${m.taxableValue.toLocaleString('en-IN')}`,
        `₹${m.outputTax.toLocaleString('en-IN')}`,
        `₹${m.itc.toLocaleString('en-IN')}`,
        `₹${m.netPayable.toLocaleString('en-IN')}`,
      ],
    })),
  ];
  y = drawTable(doc, monthlyRows, [80, 110, 100, 100, 100], M, y, W);

  // ═══ ORACLE INSIGHTS ═══
  y = ensureSpace(doc, y, 100);
  y = drawSectionHeader(doc, 'Oracle Insights', M, y, W);
  doc.fillColor(DARK).fontSize(9).font('Helvetica');
  for (const insight of report.insights) {
    y = ensureSpace(doc, y, 30);
    const lines = doc.widthOfString(insight) > CW - 20
      ? doc.heightOfString(insight, { width: CW - 20 })
      : 12;
    doc.fillColor(GRAY).font('Helvetica-Bold').fontSize(8);
    doc.text('•', M, y);
    doc.fillColor(DARK).font('Helvetica').fontSize(9);
    doc.text(insight, M + 12, y, { width: CW - 20 });
    y += lines + 6;
  }

  // ═══ RECOMMENDATIONS ═══
  y = ensureSpace(doc, y, 80);
  y = drawSectionHeader(doc, 'Recommended Actions', M, y, W);
  doc.fillColor(EMERALD).font('Helvetica-Bold').fontSize(9);
  for (const rec of report.recommendations) {
    y = ensureSpace(doc, y, 30);
    doc.fillColor(EMERALD).font('Helvetica-Bold').fontSize(9);
    doc.text('→', M, y);
    doc.fillColor(DARK).font('Helvetica').fontSize(9);
    doc.text(rec, M + 14, y, { width: CW - 20 });
    y += doc.heightOfString(rec, { width: CW - 20 }) + 6;
  }

  // ═══ FOOTER ═══
  y = ensureSpace(doc, y, 40);
  y += 10;
  doc.save();
  doc.moveTo(M, y).lineTo(W - M, y).strokeColor(LIGHT_GRAY).lineWidth(1).stroke();
  doc.restore();
  y += 8;
  doc.fillColor(GRAY).fontSize(7).font('Helvetica');
  doc.text(
    `Generated by GSTPilot Oracle CFO™ on ${new Date(report.generatedAt).toLocaleString('en-IN')} by ${report.generatedBy}. Report ID: ${report.reportId}. This report is computed from live invoice data — verify with GSTR-2B before filing.`,
    M, y, { width: CW, align: 'center' },
  );

  doc.end();
  const buffer = await pdfPromise;
  return { buffer, base64: buffer.toString('base64') };
}

// ─── PDF drawing helpers ────────────────────────────────────────────────────

function drawSectionHeader(doc: any, title: string, M: number, y: number, W: number): number {
  y = ensureSpace(doc, y, 40);
  doc.save();
  doc.rect(M, y, 6, 16).fill(EMERALD);
  doc.restore();
  doc.fillColor(DARK).fontSize(12).font('Helvetica-Bold');
  doc.text(title, M + 12, y + 1);
  return y + 24;
}

function drawTable(
  doc: any,
  rows: Array<{ cols: string[]; bold?: boolean }>,
  colWidths: number[],
  M: number,
  y: number,
  W: number,
): number {
  const rowH = 16;
  for (let i = 0; i < rows.length; i++) {
    y = ensureSpace(doc, y, rowH);
    const row = rows[i];
    const isHeader = i === 0;
    doc.save();
    if (isHeader) {
      doc.rect(M, y, colWidths.reduce((s, w) => s + w, 0), rowH).fill(BG_LIGHT);
    } else if (i % 2 === 0) {
      doc.rect(M, y, colWidths.reduce((s, w) => s + w, 0), rowH).fill('#fafafa');
    }
    doc.restore();
    let x = M;
    for (let j = 0; j < row.cols.length; j++) {
      doc.fillColor(DARK).fontSize(8).font(row.bold ? 'Helvetica-Bold' : 'Helvetica');
      doc.text(row.cols[j], x + 4, y + 4, { width: colWidths[j] - 8 });
      x += colWidths[j];
    }
    y += rowH;
  }
  return y + 8;
}

function drawKeyValueTable(
  doc: any,
  rows: Array<{ cols: string[]; bold?: boolean; highlight?: boolean }>,
  M: number,
  y: number,
  W: number,
): number {
  const CW = W - M * 2;
  const labelW = CW * 0.6;
  const valueW = CW * 0.4;
  const rowH = 16;
  for (const row of rows) {
    y = ensureSpace(doc, y, rowH);
    doc.save();
    if (row.highlight) {
      doc.rect(M, y, CW, rowH).fill(EMERALD);
    } else if (row.bold) {
      doc.rect(M, y, CW, rowH).fill(BG_LIGHT);
    }
    doc.restore();
    doc.fillColor(row.highlight ? '#ffffff' : DARK).fontSize(9).font(row.bold ? 'Helvetica-Bold' : 'Helvetica');
    doc.text(row.cols[0], M + 8, y + 4, { width: labelW - 8 });
    doc.text(row.cols[1], M + labelW, y + 4, { width: valueW - 8, align: 'right' });
    y += rowH;
  }
  return y + 8;
}

function ensureSpace(doc: any, y: number, needed: number): number {
  if (y + needed > 800) {
    doc.addPage();
    return 50;
  }
  return y;
}

// ═══════════════════════════════════════════════════════════════════════════════
// EXCEL EXPORT (xlsx / SheetJS)
// ═══════════════════════════════════════════════════════════════════════════════

export async function generateGSTReportExcel(report: GSTReport): Promise<{ buffer: Buffer; base64: string }> {
  const XLSX = await import('xlsx');
  const wb = XLSX.utils.book_new();

  // ── Sheet 1: Executive Summary ──
  const summaryAoa: (string | number)[][] = [
    ['GSTPilot — GST Report'],
    [`Report Type: ${report.intent.reportType.toUpperCase()}`],
    [`Period: ${report.intent.periodLabel} (${report.intent.startDate} to ${report.intent.endDate})`],
    [`Generated: ${new Date(report.generatedAt).toLocaleString('en-IN')} by ${report.generatedBy}`],
    [`Report ID: ${report.reportId}`],
    [],
    ['EXECUTIVE SUMMARY'],
    ['Metric', 'Value'],
    ['Taxable Turnover', report.calculations.totalTaxableTurnover],
    ['Total Output Tax', report.calculations.totalOutputTax],
    ['ITC Available', report.calculations.itcAvailable],
    ['ITC Utilized', report.calculations.itcUtilized],
    ['Net GST Payable', report.calculations.netPayable],
    ['Exempt Supplies', report.calculations.totalExempt],
    ['Zero-Rated Supplies', report.calculations.totalZeroRated],
    ['Export Supplies', report.calculations.totalExport],
    ['Refund Eligible', report.calculations.refundEligible],
    [],
    ['PERIOD DELTA'],
    ['Prior Period Output Tax', report.calculations.priorPeriodOutputTax],
    ['Current Output Tax', report.calculations.totalOutputTax],
    ['Delta', report.calculations.deltaOutputTax],
    ['Delta %', report.calculations.deltaPercent],
  ];
  const wsSummary = XLSX.utils.aoa_to_sheet(summaryAoa);
  wsSummary['!cols'] = [{ wch: 32 }, { wch: 22 }];
  XLSX.utils.book_append_sheet(wb, wsSummary, 'Summary');

  // ── Sheet 2: Sales by Slab ──
  const salesAoa: (string | number)[][] = [
    ['GST Slab', 'Invoice Count', 'Taxable Value', 'CGST', 'SGST', 'IGST', 'Cess', 'Total Tax', 'Total Amount'],
    ...report.calculations.salesBySlab.map((s) => [
      `${s.gstRate}%`, s.invoiceCount, s.taxableValue, s.cgst, s.sgst, s.igst, s.cess, s.totalTax, s.totalAmount,
    ]),
    ['TOTAL',
      report.calculations.salesBySlab.reduce((s, r) => s + r.invoiceCount, 0),
      report.calculations.totalTaxableTurnover,
      report.calculations.outputCGST,
      report.calculations.outputSGST,
      report.calculations.outputIGST,
      report.calculations.outputCess,
      report.calculations.totalOutputTax,
      report.calculations.totalTaxableTurnover + report.calculations.totalOutputTax,
    ],
  ];
  const wsSales = XLSX.utils.aoa_to_sheet(salesAoa);
  wsSales['!cols'] = [{ wch: 10 }, { wch: 14 }, { wch: 16 }, { wch: 14 }, { wch: 14 }, { wch: 14 }, { wch: 12 }, { wch: 14 }, { wch: 16 }];
  XLSX.utils.book_append_sheet(wb, wsSales, 'Sales by Slab');

  // ── Sheet 3: Purchases by Slab ──
  const purchaseAoa: (string | number)[][] = [
    ['GST Slab', 'Invoice Count', 'Taxable Value', 'CGST', 'SGST', 'IGST', 'Cess', 'Total ITC'],
    ...report.calculations.purchasesBySlab.map((s) => [
      `${s.gstRate}%`, s.invoiceCount, s.taxableValue, s.cgst, s.sgst, s.igst, s.cess, s.totalTax,
    ]),
    ['TOTAL',
      report.calculations.purchasesBySlab.reduce((s, r) => s + r.invoiceCount, 0),
      report.calculations.purchasesBySlab.reduce((s, r) => s + r.taxableValue, 0),
      report.calculations.itcCGST,
      report.calculations.itcSGST,
      report.calculations.itcIGST,
      report.calculations.itcCess,
      report.calculations.itcAvailable,
    ],
  ];
  const wsPurchase = XLSX.utils.aoa_to_sheet(purchaseAoa);
  wsPurchase['!cols'] = [{ wch: 10 }, { wch: 14 }, { wch: 16 }, { wch: 14 }, { wch: 14 }, { wch: 14 }, { wch: 12 }, { wch: 14 }];
  XLSX.utils.book_append_sheet(wb, wsPurchase, 'Purchases by Slab');

  // ── Sheet 4: GST Liability ──
  const liabilityAoa: (string | number)[][] = [
    ['Component', 'Amount (₹)'],
    ['Output CGST', report.calculations.outputCGST],
    ['Output SGST', report.calculations.outputSGST],
    ['Output IGST', report.calculations.outputIGST],
    ['Output Cess', report.calculations.outputCess],
    ['Total Output Tax', report.calculations.totalOutputTax],
    ['Less: ITC Utilized', -report.calculations.itcUtilized],
    ['Net CGST Payable', report.calculations.netCGSTPayable],
    ['Net SGST Payable', report.calculations.netSGSTPayable],
    ['Net IGST Payable', report.calculations.netIGSTPayable],
    ['Net Cess Payable', report.calculations.netCessPayable],
    ['Net GST Payable', report.calculations.netPayable],
  ];
  const wsLiability = XLSX.utils.aoa_to_sheet(liabilityAoa);
  wsLiability['!cols'] = [{ wch: 28 }, { wch: 18 }];
  XLSX.utils.book_append_sheet(wb, wsLiability, 'GST Liability');

  // ── Sheet 5: ITC Summary ──
  const itcAoa: (string | number)[][] = [
    ['Component', 'Amount (₹)'],
    ['ITC Available (CGST)', report.calculations.itcCGST],
    ['ITC Available (SGST)', report.calculations.itcSGST],
    ['ITC Available (IGST)', report.calculations.itcIGST],
    ['ITC Available (Cess)', report.calculations.itcCess],
    ['Total ITC Available', report.calculations.itcAvailable],
    ['ITC Reversed (Rule 42/43)', -report.calculations.itcReversed],
    ['ITC Utilized', report.calculations.itcUtilized],
    ['Refund Eligible', report.calculations.refundEligible],
  ];
  const wsItc = XLSX.utils.aoa_to_sheet(itcAoa);
  wsItc['!cols'] = [{ wch: 30 }, { wch: 18 }];
  XLSX.utils.book_append_sheet(wb, wsItc, 'ITC Summary');

  // ── Sheet 6: Top Customers ──
  const custAoa: (string | number)[][] = [
    ['Customer', 'GSTIN', 'Invoice Count', 'Taxable Value', 'Tax Amount', 'Total Amount'],
    ...report.topCustomers.map((c) => [c.name, c.gstin ?? '', c.invoiceCount, c.taxableValue, c.taxAmount, c.totalAmount]),
  ];
  const wsCust = XLSX.utils.aoa_to_sheet(custAoa);
  wsCust['!cols'] = [{ wch: 30 }, { wch: 18 }, { wch: 14 }, { wch: 16 }, { wch: 16 }, { wch: 16 }];
  XLSX.utils.book_append_sheet(wb, wsCust, 'Top Customers');

  // ── Sheet 7: Top Vendors ──
  const vendAoa: (string | number)[][] = [
    ['Vendor', 'GSTIN', 'Invoice Count', 'Taxable Value', 'ITC Amount', 'Total Amount'],
    ...report.topVendors.map((v) => [v.name, v.gstin ?? '', v.invoiceCount, v.taxableValue, v.taxAmount, v.totalAmount]),
  ];
  const wsVend = XLSX.utils.aoa_to_sheet(vendAoa);
  wsVend['!cols'] = [{ wch: 30 }, { wch: 18 }, { wch: 14 }, { wch: 16 }, { wch: 16 }, { wch: 16 }];
  XLSX.utils.book_append_sheet(wb, wsVend, 'Top Vendors');

  // ── Sheet 8: Validation Issues ──
  const valAoa: (string | number)[][] = [
    ['Invoice ID', 'Invoice Number', 'Severity', 'Field', 'Message', 'Value'],
    ...report.validation.issues.map((i) => [i.invoiceId, i.invoiceNumber, i.severity, i.field, i.message, i.value]),
  ];
  const wsVal = XLSX.utils.aoa_to_sheet(valAoa);
  wsVal['!cols'] = [{ wch: 26 }, { wch: 18 }, { wch: 10 }, { wch: 14 }, { wch: 60 }, { wch: 22 }];
  XLSX.utils.book_append_sheet(wb, wsVal, 'Validation Issues');

  // ── Sheet 9: Monthly Comparison ──
  const monthlyAoa: (string | number)[][] = [
    ['Period', 'Taxable Value', 'Output Tax', 'ITC', 'Net Payable'],
    ...report.monthlyComparison.map((m) => [m.periodLabel, m.taxableValue, m.outputTax, m.itc, m.netPayable]),
  ];
  const wsMonthly = XLSX.utils.aoa_to_sheet(monthlyAoa);
  wsMonthly['!cols'] = [{ wch: 14 }, { wch: 16 }, { wch: 14 }, { wch: 14 }, { wch: 14 }];
  XLSX.utils.book_append_sheet(wb, wsMonthly, 'Monthly Comparison');

  // ── Sheet 10: Cross-Checks ──
  const checkAoa: (string | number)[][] = [
    ['Check', 'Expected', 'Actual', 'Status'],
    ...report.calculations.crossChecks.map((c) => [c.label, c.expected, c.actual, c.match ? 'PASS' : 'FAIL']),
  ];
  const wsCheck = XLSX.utils.aoa_to_sheet(checkAoa);
  wsCheck['!cols'] = [{ wch: 36 }, { wch: 18 }, { wch: 18 }, { wch: 10 }];
  XLSX.utils.book_append_sheet(wb, wsCheck, 'Cross-Checks');

  // ── Sheet 11: Oracle Insights ──
  const insightsAoa: (string | number)[][] = [
    ['#', 'Insight'],
    ...report.insights.map((s, i) => [i + 1, s]),
    [],
    ['RECOMMENDED ACTIONS'],
    ...report.recommendations.map((s, i) => [i + 1, s]),
  ];
  const wsInsights = XLSX.utils.aoa_to_sheet(insightsAoa);
  wsInsights['!cols'] = [{ wch: 6 }, { wch: 100 }];
  XLSX.utils.book_append_sheet(wb, wsInsights, 'Oracle Insights');

  // Write to buffer
  const arrayBuffer = XLSX.write(wb, { type: 'array', bookType: 'xlsx' }) as ArrayBuffer;
  const buffer = Buffer.from(arrayBuffer);
  return { buffer, base64: buffer.toString('base64') };
}

// ═══════════════════════════════════════════════════════════════════════════════
// CSV EXPORT
// ═══════════════════════════════════════════════════════════════════════════════

export function generateGSTReportCSV(report: GSTReport): { buffer: Buffer; base64: string } {
  const lines: string[] = [];
  const calc = report.calculations;

  lines.push('GSTPilot GST Report');
  lines.push(`Report Type,${report.intent.reportType.toUpperCase()}`);
  lines.push(`Period,${report.intent.periodLabel}`);
  lines.push(`Date Range,${report.intent.startDate} to ${report.intent.endDate}`);
  lines.push(`Generated,${new Date(report.generatedAt).toISOString()}`);
  lines.push(`Generated By,${report.generatedBy}`);
  lines.push(`Report ID,${report.reportId}`);
  lines.push('');

  lines.push('EXECUTIVE SUMMARY');
  lines.push('Metric,Value');
  lines.push(`Taxable Turnover,${calc.totalTaxableTurnover}`);
  lines.push(`Total Output Tax,${calc.totalOutputTax}`);
  lines.push(`ITC Available,${calc.itcAvailable}`);
  lines.push(`ITC Utilized,${calc.itcUtilized}`);
  lines.push(`Net GST Payable,${calc.netPayable}`);
  lines.push(`Exempt Supplies,${calc.totalExempt}`);
  lines.push(`Zero-Rated,${calc.totalZeroRated}`);
  lines.push(`Export,${calc.totalExport}`);
  lines.push(`Refund Eligible,${calc.refundEligible}`);
  lines.push('');

  lines.push('SALES BY SLAB');
  lines.push('Slab,Invoice Count,Taxable Value,CGST,SGST,IGST,Cess,Total Tax,Total Amount');
  for (const s of calc.salesBySlab) {
    lines.push(`${s.gstRate}%,${s.invoiceCount},${s.taxableValue},${s.cgst},${s.sgst},${s.igst},${s.cess},${s.totalTax},${s.totalAmount}`);
  }
  lines.push(`TOTAL,${calc.salesBySlab.reduce((s, r) => s + r.invoiceCount, 0)},${calc.totalTaxableTurnover},${calc.outputCGST},${calc.outputSGST},${calc.outputIGST},${calc.outputCess},${calc.totalOutputTax},${calc.totalTaxableTurnover + calc.totalOutputTax}`);
  lines.push('');

  lines.push('PURCHASES BY SLAB');
  lines.push('Slab,Invoice Count,Taxable Value,CGST,SGST,IGST,Cess,Total ITC');
  for (const s of calc.purchasesBySlab) {
    lines.push(`${s.gstRate}%,${s.invoiceCount},${s.taxableValue},${s.cgst},${s.sgst},${s.igst},${s.cess},${s.totalTax}`);
  }
  lines.push(`TOTAL,${calc.purchasesBySlab.reduce((s, r) => s + r.invoiceCount, 0)},${calc.purchasesBySlab.reduce((s, r) => s + r.taxableValue, 0)},${calc.itcCGST},${calc.itcSGST},${calc.itcIGST},${calc.itcCess},${calc.itcAvailable}`);
  lines.push('');

  lines.push('GST LIABILITY');
  lines.push('Component,Amount');
  lines.push(`Output CGST,${calc.outputCGST}`);
  lines.push(`Output SGST,${calc.outputSGST}`);
  lines.push(`Output IGST,${calc.outputIGST}`);
  lines.push(`Output Cess,${calc.outputCess}`);
  lines.push(`Total Output Tax,${calc.totalOutputTax}`);
  lines.push(`Less: ITC Utilized,-${calc.itcUtilized}`);
  lines.push(`Net CGST Payable,${calc.netCGSTPayable}`);
  lines.push(`Net SGST Payable,${calc.netSGSTPayable}`);
  lines.push(`Net IGST Payable,${calc.netIGSTPayable}`);
  lines.push(`Net Cess Payable,${calc.netCessPayable}`);
  lines.push(`Net GST Payable,${calc.netPayable}`);
  lines.push('');

  lines.push('TOP CUSTOMERS');
  lines.push('Customer,GSTIN,Invoice Count,Taxable Value,Tax Amount,Total Amount');
  for (const c of report.topCustomers) {
    lines.push(`"${c.name}",${c.gstin ?? ''},${c.invoiceCount},${c.taxableValue},${c.taxAmount},${c.totalAmount}`);
  }
  lines.push('');

  lines.push('TOP VENDORS');
  lines.push('Vendor,GSTIN,Invoice Count,Taxable Value,ITC Amount,Total Amount');
  for (const v of report.topVendors) {
    lines.push(`"${v.name}",${v.gstin ?? ''},${v.invoiceCount},${v.taxableValue},${v.taxAmount},${v.totalAmount}`);
  }
  lines.push('');

  lines.push('VALIDATION SUMMARY');
  lines.push(`Invoices Checked,${report.validation.totalChecked}`);
  lines.push(`Passed,${report.validation.passed}`);
  lines.push(`Critical Issues,${report.validation.criticalCount}`);
  lines.push(`Warnings,${report.validation.warningCount}`);
  lines.push(`Info,${report.validation.infoCount}`);
  lines.push(`Duplicate Invoice Numbers,${report.validation.duplicateInvoiceNumbers.length}`);
  lines.push(`Invalid GSTINs,${report.validation.invalidGstins.length}`);
  lines.push(`Future-Dated Invoices,${report.validation.futureDatedInvoices.length}`);
  lines.push(`Reverse-Charge Invoices,${report.validation.reverseChargeInvoices.length}`);
  lines.push(`Exempt Invoices,${report.validation.exemptInvoices.length}`);
  lines.push(`Zero-Rated Invoices,${report.validation.zeroRatedInvoices.length}`);
  lines.push(`Export Invoices,${report.validation.exportInvoices.length}`);
  lines.push('');

  if (report.validation.issues.length > 0) {
    lines.push('VALIDATION ISSUES');
    lines.push('Invoice ID,Invoice Number,Severity,Field,Message,Value');
    for (const i of report.validation.issues) {
      lines.push(`${i.invoiceId},"${i.invoiceNumber}",${i.severity},${i.field},"${i.message.replace(/"/g, '""')}","${i.value}"`);
    }
    lines.push('');
  }

  lines.push('CROSS-CHECKS');
  lines.push('Check,Expected,Actual,Status');
  for (const c of calc.crossChecks) {
    lines.push(`"${c.label}",${c.expected},${c.actual},${c.match ? 'PASS' : 'FAIL'}`);
  }
  lines.push('');

  lines.push('MONTHLY COMPARISON');
  lines.push('Period,Taxable Value,Output Tax,ITC,Net Payable');
  for (const m of report.monthlyComparison) {
    lines.push(`${m.periodLabel},${m.taxableValue},${m.outputTax},${m.itc},${m.netPayable}`);
  }
  lines.push('');

  lines.push('ORACLE INSIGHTS');
  lines.push('#,Insight');
  report.insights.forEach((s, i) => lines.push(`${i + 1},"${s.replace(/"/g, '""')}"`));
  lines.push('');
  lines.push('RECOMMENDED ACTIONS');
  lines.push('#,Action');
  report.recommendations.forEach((s, i) => lines.push(`${i + 1},"${s.replace(/"/g, '""')}"`));

  const csv = lines.join('\n');
  const buffer = Buffer.from(csv, 'utf-8');
  return { buffer, base64: buffer.toString('base64') };
}
