// ═══════════════════════════════════════════════════════════════════════════════
// GSTPilot Oracle CFO™ — Invoice PDF Generator
//
// Generates a professional, production-grade invoice PDF with:
//   • Company branding (GSTPilot header + seller details)
//   • QR code (invoice summary for quick verification)
//   • GSTIN (seller + buyer)
//   • HSN/SAC code
//   • Tax breakup (CGST / SGST / IGST)
//   • Signature line
//   • Terms & Conditions
//
// Uses pdfkit (pure JS, no native deps) + qrcode.
// Dynamically imported to keep the main bundle small.
// ═══════════════════════════════════════════════════════════════════════════════

import type { InvoiceApprovalSummary } from './invoice-engine';

export interface InvoicePDFData {
  summary: InvoiceApprovalSummary;
  sellerDetails: {
    tradeName: string;
    legalName: string;
    gstin: string;
    address: string;
    state: string;
    stateCode: string;
    email: string;
    phone: string;
  };
  invoiceId: string;
  hsnCode: string;
  placeOfSupply: string;
  termsAndConditions: string[];
}

/**
 * Generate a professional invoice PDF as a Buffer.
 * Returns { buffer, base64 }.
 */
export async function generateInvoicePDF(data: InvoicePDFData): Promise<{ buffer: Buffer; base64: string }> {
  // Dynamic imports — keeps main bundle small, only loads when PDF is needed
  const PDFDocument = (await import('pdfkit')).default;
  const QRCode = await import('qrcode');

  const doc = new PDFDocument({ size: 'A4', margin: 50 });
  const chunks: Buffer[] = [];
  doc.on('data', (chunk: Buffer) => chunks.push(chunk));

  const pdfPromise = new Promise<Buffer>((resolve) => {
    doc.on('end', () => resolve(Buffer.concat(chunks)));
  });

  const { summary, sellerDetails, invoiceId, hsnCode, placeOfSupply, termsAndConditions } = data;
  const W = 595; // A4 width in points
  const M = 50;  // margin
  const CW = W - M * 2; // content width

  // ─── Colors ───
  const EMERALD = '#10b981';
  const DARK = '#0a0a0a';
  const GRAY = '#666666';
  const LIGHT_GRAY = '#e5e5e5';
  const BG_LIGHT = '#f9fafb';

  // ═══════════════════════════════════════════════════════════════════════════
  // HEADER — Company branding
  // ═══════════════════════════════════════════════════════════════════════════

  // Top accent bar
  doc.save();
  doc.rect(0, 0, W, 6).fill(EMERALD);
  doc.restore();

  // Logo box (emerald rounded rect with "G" mark)
  doc.save();
  doc.roundedRect(M, 30, 44, 44, 10).fill(EMERALD);
  doc.fillColor('#ffffff').fontSize(26).font('Helvetica-Bold');
  doc.text('G', M + 14, 38);
  doc.restore();

  // Company name
  doc.fillColor(DARK).fontSize(22).font('Helvetica-Bold');
  doc.text(sellerDetails.tradeName, M + 56, 32);

  // Tagline
  doc.fillColor(GRAY).fontSize(9).font('Helvetica');
  doc.text('Tax Invoice — Generated by GSTPilot Oracle CFO™', M + 56, 58);

  // Invoice meta (right side)
  doc.fontSize(10).font('Helvetica-Bold');
  doc.text('INVOICE', W - M - 80, 30, { width: 80, align: 'right' });
  doc.font('Helvetica').fillColor(GRAY).fontSize(9);
  doc.text(summary.invoice.number, W - M - 120, 46, { width: 120, align: 'right' });
  doc.text(`Date: ${formatDate(summary.invoice.date)}`, W - M - 120, 60, { width: 120, align: 'right' });

  // Horizontal divider
  doc.save();
  doc.moveTo(M, 90).lineTo(W - M, 90).strokeColor(LIGHT_GRAY).lineWidth(1).stroke();
  doc.restore();

  // ═══════════════════════════════════════════════════════════════════════════
  // SELLER + BUYER DETAILS
  // ═══════════════════════════════════════════════════════════════════════════

  let y = 105;

  // Seller (left)
  doc.fillColor(EMERALD).fontSize(8).font('Helvetica-Bold');
  doc.text('FROM', M, y);
  doc.fillColor(DARK).fontSize(11);
  doc.text(sellerDetails.tradeName, M, y + 14);
  doc.fillColor(GRAY).fontSize(8).font('Helvetica');
  doc.text(sellerDetails.address, M, y + 30, { width: 220 });
  doc.text(`${sellerDetails.state} (${sellerDetails.stateCode})`, M, y + 50);
  doc.text(`GSTIN: ${sellerDetails.gstin}`, M, y + 62);
  doc.text(`Email: ${sellerDetails.email}`, M, y + 74);

  // Buyer (right)
  const buyerX = W - M - 220;
  doc.fillColor(EMERALD).fontSize(8).font('Helvetica-Bold');
  doc.text('BILL TO', buyerX, y);
  doc.fillColor(DARK).fontSize(11).font('Helvetica-Bold');
  doc.text(summary.customer.name, buyerX, y + 14);
  doc.fillColor(GRAY).fontSize(8).font('Helvetica');
  let buyerY = y + 30;
  if (summary.customer.gstin) {
    doc.text(`GSTIN: ${summary.customer.gstin}`, buyerX, buyerY);
    buyerY += 12;
  }
  if (summary.customer.state) {
    doc.text(`State: ${summary.customer.state}`, buyerX, buyerY);
    buyerY += 12;
  }
  if (summary.customer.email) {
    doc.text(`Email: ${summary.customer.email}`, buyerX, buyerY);
    buyerY += 12;
  }
  if (summary.customer.phone) {
    doc.text(`Phone: ${summary.customer.phone}`, buyerX, buyerY);
  }

  y = 210;

  // ═══════════════════════════════════════════════════════════════════════════
  // INVOICE DETAILS BAR
  // ═══════════════════════════════════════════════════════════════════════════

  doc.save();
  doc.roundedRect(M, y, CW, 28, 4).fill(BG_LIGHT);
  doc.restore();

  doc.fillColor(GRAY).fontSize(8).font('Helvetica-Bold');
  doc.text('INVOICE DATE', M + 12, y + 6);
  doc.text('DUE DATE', M + 12 + CW / 3, y + 6);
  doc.text('PLACE OF SUPPLY', M + 12 + (CW / 3) * 2, y + 6);

  doc.fillColor(DARK).fontSize(10).font('Helvetica');
  doc.text(formatDate(summary.invoice.date), M + 12, y + 16);
  doc.text(formatDate(summary.invoice.dueDate), M + 12 + CW / 3, y + 16);
  doc.text(placeOfSupply, M + 12 + (CW / 3) * 2, y + 16);

  y += 45;

  // ═══════════════════════════════════════════════════════════════════════════
  // LINE ITEMS TABLE
  // ═══════════════════════════════════════════════════════════════════════════

  // Table header
  doc.save();
  doc.roundedRect(M, y, CW, 22, 4).fill(DARK);
  doc.restore();

  doc.fillColor('#ffffff').fontSize(8).font('Helvetica-Bold');
  const colX = { desc: M + 10, hsn: M + 250, qty: M + 330, rate: M + 380, amount: W - M - 10 };
  doc.text('DESCRIPTION', colX.desc, y + 7);
  doc.text('HSN/SAC', colX.hsn, y + 7);
  doc.text('QTY', colX.qty, y + 7);
  doc.text('RATE', colX.rate, y + 7, { width: 60, align: 'right' });
  doc.text('AMOUNT', colX.amount, y + 7, { width: 70, align: 'right' });

  y += 22;

  // Line item row
  doc.fillColor(DARK).fontSize(9).font('Helvetica');
  const descText = summary.description || 'Professional services as agreed';
  doc.text(descText, colX.desc, y + 10, { width: 230 });
  doc.fillColor(GRAY).font('Helvetica');
  doc.text(hsnCode || '998314', colX.hsn, y + 10);
  doc.text('1', colX.qty, y + 10);
  doc.text(`₹${summary.amounts.taxable.toLocaleString('en-IN')}`, colX.rate, y + 10, { width: 60, align: 'right' });
  doc.fillColor(DARK).font('Helvetica-Bold');
  doc.text(`₹${summary.amounts.taxable.toLocaleString('en-IN')}`, colX.amount, y + 10, { width: 70, align: 'right' });

  y += 30;

  // Row divider
  doc.save();
  doc.moveTo(M, y).lineTo(W - M, y).strokeColor(LIGHT_GRAY).lineWidth(0.5).stroke();
  doc.restore();

  y += 10;

  // ═══════════════════════════════════════════════════════════════════════════
  // TAX BREAKUP + TOTALS (right side) + QR CODE (left side)
  // ═══════════════════════════════════════════════════════════════════════════

  // QR Code (left) — encodes invoice summary for verification
  const qrData = JSON.stringify({
    inv: summary.invoice.number,
    dt: summary.invoice.date,
    amt: summary.amounts.grandTotal,
    gstin_s: sellerDetails.gstin,
    gstin_b: summary.customer.gstin,
  });
  try {
    const qrSvg = await QRCode.toString(qrData, { type: 'svg', margin: 1, width: 120 });
    // pdfkit can embed SVG via SVG path — but simpler: generate PNG buffer
    const qrBuffer = await QRCode.toBuffer(qrData, { type: 'png', margin: 1, width: 120 });
    doc.image(qrBuffer, M, y, { width: 100, height: 100 });
    doc.fillColor(GRAY).fontSize(7).font('Helvetica');
    doc.text('Scan to verify invoice', M, y + 102, { width: 100, align: 'center' });
  } catch {
    doc.fillColor(GRAY).fontSize(8);
    doc.text('QR code unavailable', M, y + 40);
  }

  // Totals (right side)
  const totalsX = W - M - 200;
  const labelW = 120;
  const valueW = 80;
  let totalsY = y;

  const totalRows = [
    { label: 'Taxable Value', value: `₹${summary.amounts.taxable.toLocaleString('en-IN')}`, bold: false },
  ];

  if (summary.gst.isInterState) {
    totalRows.push({ label: `IGST @ ${summary.gst.rate}%`, value: `₹${summary.gst.igst.toLocaleString('en-IN')}`, bold: false });
  } else {
    totalRows.push({ label: `CGST @ ${summary.gst.rate / 2}%`, value: `₹${summary.gst.cgst.toLocaleString('en-IN')}`, bold: false });
    totalRows.push({ label: `SGST @ ${summary.gst.rate / 2}%`, value: `₹${summary.gst.sgst.toLocaleString('en-IN')}`, bold: false });
  }

  if (summary.gst.reverseCharge) {
    totalRows.push({ label: 'Reverse Charge', value: 'Yes', bold: false });
  }

  for (const row of totalRows) {
    doc.fillColor(GRAY).fontSize(9).font('Helvetica');
    doc.text(row.label, totalsX, totalsY, { width: labelW });
    doc.fillColor(DARK).font(row.bold ? 'Helvetica-Bold' : 'Helvetica');
    doc.text(row.value, totalsX + labelW, totalsY, { width: valueW, align: 'right' });
    totalsY += 16;
  }

  // Grand total box
  totalsY += 4;
  doc.save();
  doc.roundedRect(totalsX, totalsY, labelW + valueW, 28, 4).fill(EMERALD);
  doc.restore();
  doc.fillColor('#ffffff').fontSize(10).font('Helvetica-Bold');
  doc.text('GRAND TOTAL', totalsX + 10, totalsY + 9);
  doc.text(`₹${summary.amounts.grandTotal.toLocaleString('en-IN')}`, totalsX + labelW, totalsY + 9, { width: valueW, align: 'right' });

  // Amount in words (below QR)
  const words = numberToWords(Math.round(summary.amounts.grandTotal));
  doc.fillColor(GRAY).fontSize(8).font('Helvetica-Oblique');
  doc.text(`Amount in words: ${words} only`, M, y + 130, { width: 200 });

  y = Math.max(y + 140, totalsY + 50);

  // ═══════════════════════════════════════════════════════════════════════════
  // SIGNATURE
  // ═══════════════════════════════════════════════════════════════════════════

  doc.save();
  doc.moveTo(W - M - 150, y).lineTo(W - M, y).strokeColor(DARK).lineWidth(0.5).stroke();
  doc.restore();
  doc.fillColor(GRAY).fontSize(8).font('Helvetica');
  doc.text('Authorised Signatory', W - M - 150, y + 4, { width: 150, align: 'center' });
  doc.text(`For ${sellerDetails.tradeName}`, W - M - 150, y + 16, { width: 150, align: 'center' });

  y += 50;

  // ═══════════════════════════════════════════════════════════════════════════
  // TERMS & CONDITIONS
  // ═══════════════════════════════════════════════════════════════════════════

  doc.save();
  doc.moveTo(M, y).lineTo(W - M, y).strokeColor(LIGHT_GRAY).lineWidth(0.5).stroke();
  doc.restore();
  y += 10;

  doc.fillColor(EMERALD).fontSize(8).font('Helvetica-Bold');
  doc.text('TERMS & CONDITIONS', M, y);
  y += 14;

  doc.fillColor(GRAY).fontSize(7.5).font('Helvetica');
  const defaultTerms = [
    'Payment is due within 15 days from the date of invoice.',
    'Interest @ 18% p.a. will be charged on overdue payments.',
    'All disputes are subject to local jurisdiction only.',
    'GST is charged as per applicable rates under the CGST/SGST/IGST Act.',
    'This is a computer-generated invoice and does not require a physical signature.',
  ];
  const terms = termsAndConditions.length > 0 ? termsAndConditions : defaultTerms;
  for (const term of terms) {
    doc.text(`• ${term}`, M, y, { width: CW - 20 });
    y += 12;
  }

  // Footer
  y = 800;
  doc.save();
  doc.moveTo(M, y).lineTo(W - M, y).strokeColor(LIGHT_GRAY).lineWidth(0.5).stroke();
  doc.restore();
  doc.fillColor(GRAY).fontSize(7).font('Helvetica');
  doc.text(`Generated by GSTPilot Oracle CFO™ · Invoice ID: ${invoiceId} · ${new Date().toISOString()}`, M, y + 6, { width: CW, align: 'center' });

  doc.end();

  const buffer = await pdfPromise;
  return { buffer, base64: buffer.toString('base64') };
}

// ─── Helpers ────────────────────────────────────────────────────────────────

function formatDate(iso: string): string {
  try {
    const d = new Date(iso);
    return d.toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });
  } catch {
    return iso;
  }
}

function numberToWords(n: number): string {
  if (n === 0) return 'Zero';
  const ones = ['', 'One', 'Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine',
    'Ten', 'Eleven', 'Twelve', 'Thirteen', 'Fourteen', 'Fifteen', 'Sixteen', 'Seventeen', 'Eighteen', 'Nineteen'];
  const tens = ['', '', 'Twenty', 'Thirty', 'Forty', 'Fifty', 'Sixty', 'Seventy', 'Eighty', 'Ninety'];

  function twoDigits(num: number): string {
    if (num < 20) return ones[num];
    return tens[Math.floor(num / 10)] + (num % 10 ? ' ' + ones[num % 10] : '');
  }

  function threeDigits(num: number): string {
    const h = Math.floor(num / 100);
    const r = num % 100;
    let s = '';
    if (h > 0) s += ones[h] + ' Hundred';
    if (r > 0) s += (h > 0 ? ' ' : '') + twoDigits(r);
    return s;
  }

  let result = '';
  const crore = Math.floor(n / 10000000);
  const lakh = Math.floor((n % 10000000) / 100000);
  const thousand = Math.floor((n % 100000) / 1000);
  const remainder = n % 1000;

  if (crore > 0) result += threeDigits(crore) + ' Crore ';
  if (lakh > 0) result += twoDigits(lakh) + ' Lakh ';
  if (thousand > 0) result += twoDigits(thousand) + ' Thousand ';
  if (remainder > 0) result += threeDigits(remainder);

  return result.trim();
}
