// ═══════════════════════════════════════════════════════════════════════════════
// GSTPILOT GLOBAL CONNECTIVITY FABRIC™ — CONNECTOR REGISTRY
// The production catalog of REAL connectors across every external business system.
// Every entry corresponds to a real-world service, real provider, real API.
// (No mocks — these are real names of real services with real capabilities.)
// ═══════════════════════════════════════════════════════════════════════════════

import type { ConnectorCategory, ConnectorDefinition } from './types';

// ─── BANKING NETWORK™ ───────────────────────────────────────────────────────────
const BANKING_CONNECTORS: ConnectorDefinition[] = [
  { key: 'bank.sbi', provider: 'SBI', name: 'State Bank of India', category: 'banking', description: 'Corporate & retail banking — balances, transactions, UPI, IMPS, RTGS, NEFT, cards, escrow.', capabilities: ['Balance', 'Transactions', 'UPI', 'IMPS', 'RTGS', 'NEFT', 'Cards', 'Corporate Banking'], authMethods: ['oauth2', 'api_key'], regions: ['IN'], certified: true, popularity: 98, syncIntervalDefault: '15m', realTime: true },
  { key: 'bank.hdfc', provider: 'HDFC', name: 'HDFC Bank', category: 'banking', description: 'Corporate banking, smart hubs, BBPS, API banking, cash management.', capabilities: ['Balance', 'Transactions', 'Cash Management', 'API Banking', 'BBPS'], authMethods: ['oauth2', 'api_key'], regions: ['IN'], certified: true, popularity: 96, syncIntervalDefault: '15m', realTime: true },
  { key: 'bank.icici', provider: 'ICICI', name: 'ICICI Bank', category: 'banking', description: 'B2B API banking, corporate connectivity, escrow, cash management.', capabilities: ['Balance', 'Transactions', 'Corporate APIs', 'Escrow', 'Cash Management'], authMethods: ['oauth2', 'api_key'], regions: ['IN'], certified: true, popularity: 95, syncIntervalDefault: '15m', realTime: true },
  { key: 'bank.axis', provider: 'Axis', name: 'Axis Bank', category: 'banking', description: 'Corporate API banking, payment collections, payouts.', capabilities: ['Balance', 'Transactions', 'Collections', 'Payouts', 'API Banking'], authMethods: ['oauth2', 'api_key'], regions: ['IN'], certified: true, popularity: 92, syncIntervalDefault: '15m', realTime: true },
  { key: 'bank.kotak', provider: 'Kotak', name: 'Kotak Mahindra Bank', category: 'banking', description: 'Corporate banking, payment gateway, treasury APIs.', capabilities: ['Balance', 'Transactions', 'Payment Gateway', 'Treasury'], authMethods: ['oauth2', 'api_key'], regions: ['IN'], certified: true, popularity: 88, syncIntervalDefault: '15m', realTime: true },
  { key: 'bank.yes', provider: 'Yes Bank', name: 'Yes Bank', category: 'banking', description: 'Corporate API banking, UPI collections, BBPS.', capabilities: ['Balance', 'Transactions', 'UPI Collections', 'BBPS'], authMethods: ['oauth2', 'api_key'], regions: ['IN'], certified: true, popularity: 82, syncIntervalDefault: '15m', realTime: true },
  { key: 'bank.idfc', provider: 'IDFC First', name: 'IDFC First Bank', category: 'banking', description: 'Corporate banking, current account APIs, MSME banking.', capabilities: ['Balance', 'Transactions', 'MSME Banking'], authMethods: ['oauth2', 'api_key'], regions: ['IN'], certified: true, popularity: 78, syncIntervalDefault: '15m', realTime: true },
  { key: 'bank.federal', provider: 'Federal Bank', name: 'Federal Bank', category: 'banking', description: 'Corporate API banking, trade finance, NRI services.', capabilities: ['Balance', 'Transactions', 'Trade Finance'], authMethods: ['oauth2', 'api_key'], regions: ['IN'], certified: true, popularity: 70, syncIntervalDefault: '15m', realTime: true },
  { key: 'bank.pnb', provider: 'PNB', name: 'Punjab National Bank', category: 'banking', description: 'Corporate banking, government transactions, PSB loans.', capabilities: ['Balance', 'Transactions', 'Gov Transactions'], authMethods: ['oauth2', 'api_key'], regions: ['IN'], certified: true, popularity: 75, syncIntervalDefault: '15m', realTime: false },
  { key: 'bank.canara', provider: 'Canara', name: 'Canara Bank', category: 'banking', description: 'Corporate banking, MSME loans, trade finance.', capabilities: ['Balance', 'Transactions', 'MSME Loans', 'Trade Finance'], authMethods: ['oauth2', 'api_key'], regions: ['IN'], certified: true, popularity: 72, syncIntervalDefault: '15m', realTime: false },
  { key: 'bank.bob', provider: 'Bank of Baroda', name: 'Bank of Baroda', category: 'banking', description: 'Corporate banking, international banking, treasury.', capabilities: ['Balance', 'Transactions', 'International Banking', 'Treasury'], authMethods: ['oauth2', 'api_key'], regions: ['IN'], certified: true, popularity: 73, syncIntervalDefault: '15m', realTime: false },
  { key: 'bank.rbi.aa', provider: 'RBI Account Aggregator', name: 'RBI Account Aggregator', category: 'banking', description: 'RBI-regulated Account Aggregator network — consent-based financial data sharing.', capabilities: ['Consent-based Data', 'Bank Statements', 'Mutual Funds', 'Deposits', 'Insurance'], authMethods: ['oauth2', 'certificate'], regions: ['IN'], certified: true, popularity: 90, syncIntervalDefault: '1h', realTime: false },
  { key: 'bank.upi', provider: 'UPI', name: 'UPI (NPCI)', category: 'banking', description: 'Unified Payments Interface — collect, pay, validate VPA, mandates.', capabilities: ['Collect', 'Pay', 'VPA Validate', 'Mandates', 'Subscriptions'], authMethods: ['api_key', 'certificate'], regions: ['IN'], certified: true, popularity: 99, syncIntervalDefault: '5m', realTime: true },
  { key: 'bank.imps', provider: 'IMPS', name: 'IMPS (NPCI)', category: 'banking', description: 'Immediate Payment Service — 24x7 instant fund transfer.', capabilities: ['Instant Transfer', 'MMID'], authMethods: ['api_key'], regions: ['IN'], certified: true, popularity: 88, syncIntervalDefault: '5m', realTime: true },
  { key: 'bank.rtgs', provider: 'RTGS', name: 'RTGS (RBI)', category: 'banking', description: 'Real Time Gross Settlement — high-value interbank transfers.', capabilities: ['High-Value Transfer', 'Bulk'], authMethods: ['api_key', 'certificate'], regions: ['IN'], certified: true, popularity: 80, syncIntervalDefault: '15m', realTime: false },
  { key: 'bank.neft', provider: 'NEFT', name: 'NEFT (RBI)', category: 'banking', description: 'National Electronic Funds Transfer — batched retail transfers.', capabilities: ['Retail Transfer', 'Batched'], authMethods: ['api_key'], regions: ['IN'], certified: true, popularity: 85, syncIntervalDefault: '15m', realTime: false },
  { key: 'bank.escrow', provider: 'Escrow Services', name: 'Escrow Banking', category: 'banking', description: 'Escrow accounts for transactions, M&A, real estate, marketplace settlements.', capabilities: ['Escrow Account', 'Milestone Release', 'Dispute Resolution'], authMethods: ['oauth2', 'api_key'], regions: ['IN'], certified: true, popularity: 65, syncIntervalDefault: '1h', realTime: false },
  { key: 'bank.corporate', provider: 'Corporate Banking', name: 'Corporate Banking APIs', category: 'banking', description: 'Unified corporate banking — multi-bank cash pooling, sweeping, treasury.', capabilities: ['Cash Pooling', 'Sweeping', 'Treasury', 'Multi-Bank'], authMethods: ['oauth2', 'certificate'], regions: ['IN'], certified: true, popularity: 70, syncIntervalDefault: '15m', realTime: true },
];

// ─── GOVERNMENT NETWORK™ ─────────────────────────────────────────────────────────
const GOVERNMENT_CONNECTORS: ConnectorDefinition[] = [
  { key: 'gov.gstn', provider: 'GSTN', name: 'GST Portal (GSTN)', category: 'government', description: 'GST profile, GSTR-1/3B/2B/9, ITC, filing status, notices, e-invoice, e-way bill.', capabilities: ['GST Profile', 'GSTR-1', 'GSTR-3B', 'GSTR-2B', 'GSTR-9', 'ITC', 'Filing Status', 'Notices', 'E-Invoice', 'E-Way Bill'], authMethods: ['oauth2', 'api_key'], regions: ['IN'], certified: true, popularity: 100, syncIntervalDefault: '15m', realTime: true },
  { key: 'gov.incometax', provider: 'Income Tax', name: 'Income Tax Department', category: 'government', description: 'PAN/TAN validation, TDS returns, ITR status, 26AS, AIS/TIS, refunds.', capabilities: ['PAN/TAN Validate', 'TDS Returns', 'ITR Status', '26AS', 'AIS/TIS', 'Refunds'], authMethods: ['oauth2', 'api_key'], regions: ['IN'], certified: true, popularity: 95, syncIntervalDefault: '1h', realTime: false },
  { key: 'gov.mca', provider: 'MCA', name: 'Ministry of Corporate Affairs', category: 'government', description: 'Company master data, filings, directorships, charges, annual returns.', capabilities: ['Company Master', 'Filings', 'Directorships', 'Charges', 'Annual Returns'], authMethods: ['api_key'], regions: ['IN'], certified: true, popularity: 88, syncIntervalDefault: '6h', realTime: false },
  { key: 'gov.icegate', provider: 'ICEGATE', name: 'ICEGATE (Customs)', category: 'government', description: 'Import/export declarations, Bill of Entry, shipping bills, DGFT linkage.', capabilities: ['Bill of Entry', 'Shipping Bill', 'Import/Export', 'Customs Duty'], authMethods: ['api_key', 'certificate'], regions: ['IN'], certified: true, popularity: 65, syncIntervalDefault: '1h', realTime: false },
  { key: 'gov.dgft', provider: 'DGFT', name: 'DGFT (Foreign Trade)', category: 'government', description: 'IEC, export incentives, advance authorizations, EPCG schemes.', capabilities: ['IEC', 'Export Incentives', 'Advance Authorization', 'EPCG'], authMethods: ['api_key'], regions: ['IN'], certified: true, popularity: 55, syncIntervalDefault: '6h', realTime: false },
  { key: 'gov.epfo', provider: 'EPFO', name: 'Employees Provident Fund', category: 'government', description: 'PF accounts, ECR filing, UAN, member details, claims.', capabilities: ['PF Account', 'ECR Filing', 'UAN', 'Claims'], authMethods: ['api_key', 'certificate'], regions: ['IN'], certified: true, popularity: 78, syncIntervalDefault: 'daily', realTime: false },
  { key: 'gov.esic', provider: 'ESIC', name: 'Employees State Insurance', category: 'government', description: 'ESI registration, contributions, employee enrolment, claims.', capabilities: ['ESI Reg', 'Contributions', 'Enrolment', 'Claims'], authMethods: ['api_key'], regions: ['IN'], certified: true, popularity: 70, syncIntervalDefault: 'daily', realTime: false },
  { key: 'gov.tds', provider: 'TDS/TRACES', name: 'TDS (TRACES)', category: 'government', description: 'TDS returns, challans, default notices, 16A, 26AS reconciliation.', capabilities: ['TDS Returns', 'Challans', '16A', '26AS Reconciliation'], authMethods: ['api_key', 'certificate'], regions: ['IN'], certified: true, popularity: 82, syncIntervalDefault: '1h', realTime: false },
  { key: 'gov.eway', provider: 'E-Way Bill', name: 'E-Way Bill (GSTN)', category: 'government', description: 'Generate, cancel, extend e-way bills; transporter assignment; PART-B updates.', capabilities: ['Generate', 'Cancel', 'Extend', 'Transporter', 'PART-B'], authMethods: ['api_key'], regions: ['IN'], certified: true, popularity: 88, syncIntervalDefault: '15m', realTime: true },
  { key: 'gov.einvoice', provider: 'E-Invoice', name: 'E-Invoice (IRP)', category: 'government', description: 'Invoice Reference Number (IRN), QR code generation, e-invoice cancellation.', capabilities: ['IRN Generate', 'QR Code', 'Cancel', 'Bulk'], authMethods: ['api_key', 'certificate'], regions: ['IN'], certified: true, popularity: 92, syncIntervalDefault: '5m', realTime: true },
  { key: 'gov.udyam', provider: 'Udyam', name: 'Udyam (MSME) Registration', category: 'government', description: 'MSME/Udyam registration, classification, status verification.', capabilities: ['Udyam Reg', 'Classification', 'Status'], authMethods: ['api_key'], regions: ['IN'], certified: true, popularity: 68, syncIntervalDefault: 'daily', realTime: false },
  { key: 'gov.gem', provider: 'GeM', name: 'Government e-Marketplace', category: 'government', description: 'Government procurement, bids, contracts, vendor rating, payments.', capabilities: ['Procurement', 'Bids', 'Contracts', 'Vendor Rating'], authMethods: ['oauth2', 'api_key'], regions: ['IN'], certified: true, popularity: 60, syncIntervalDefault: '1h', realTime: false },
  { key: 'gov.procurement', provider: 'Govt Procurement', name: 'Government Procurement Network', category: 'government', description: 'CPPP, state procurement portals, tender discovery, EMD, bid submission.', capabilities: ['Tenders', 'EMD', 'Bid Submission'], authMethods: ['oauth2'], regions: ['IN'], certified: true, popularity: 50, syncIntervalDefault: '6h', realTime: false },
];

// ─── COMMUNICATION FABRIC™ ───────────────────────────────────────────────────────
const COMMUNICATION_CONNECTORS: ConnectorDefinition[] = [
  { key: 'comm.whatsapp', provider: 'WhatsApp', name: 'WhatsApp Business API', category: 'communication', description: 'Send/receive WhatsApp messages, templates, media, interactive, business chat.', capabilities: ['Send', 'Receive', 'Templates', 'Media', 'Interactive'], authMethods: ['bearer', 'api_key'], regions: ['global'], certified: true, popularity: 98, syncIntervalDefault: 'realtime', realTime: true },
  { key: 'comm.email', provider: 'Email (IMAP/SMTP)', name: 'Email — IMAP/SMTP/Gmail/Outlook', category: 'communication', description: 'Read and send emails across Gmail, Outlook, Yahoo, custom IMAP/SMTP.', capabilities: ['Read', 'Send', 'Attachments', 'Search', 'Labels'], authMethods: ['oauth2', 'basic'], regions: ['global'], certified: true, popularity: 99, syncIntervalDefault: '5m', realTime: true },
  { key: 'comm.sms', provider: 'SMS', name: 'SMS (Twilio/MSG91)', category: 'communication', description: 'Send SMS via Twilio, MSG91, Fast2SMS, Textlocal — transactional & marketing.', capabilities: ['Transactional SMS', 'Marketing SMS', 'OTP', 'Bulk'], authMethods: ['api_key', 'bearer'], regions: ['global'], certified: true, popularity: 85, syncIntervalDefault: 'realtime', realTime: true },
  { key: 'comm.slack', provider: 'Slack', name: 'Slack', category: 'communication', description: 'Slack workspaces — channels, DMs, threads, file sharing, app mentions.', capabilities: ['Channels', 'DMs', 'Threads', 'Files', 'Mentions'], authMethods: ['oauth2', 'bearer'], regions: ['global'], certified: true, popularity: 90, syncIntervalDefault: 'realtime', realTime: true },
  { key: 'comm.teams', provider: 'Microsoft Teams', name: 'Microsoft Teams', category: 'communication', description: 'Teams chats, channels, meetings, file sharing, bots.', capabilities: ['Chats', 'Channels', 'Meetings', 'Files', 'Bots'], authMethods: ['oauth2'], regions: ['global'], certified: true, popularity: 88, syncIntervalDefault: 'realtime', realTime: true },
  { key: 'comm.discord', provider: 'Discord', name: 'Discord', category: 'communication', description: 'Discord servers — text/voice channels, roles, webhooks, slash commands.', capabilities: ['Text', 'Voice', 'Roles', 'Webhooks', 'Slash Commands'], authMethods: ['oauth2', 'bearer'], regions: ['global'], certified: true, popularity: 70, syncIntervalDefault: 'realtime', realTime: true },
  { key: 'comm.zoom', provider: 'Zoom', name: 'Zoom', category: 'communication', description: 'Zoom meetings, webinars, recordings, transcripts, chat.', capabilities: ['Meetings', 'Webinars', 'Recordings', 'Transcripts'], authMethods: ['oauth2'], regions: ['global'], certified: true, popularity: 85, syncIntervalDefault: '15m', realTime: false },
  { key: 'comm.gmeet', provider: 'Google Meet', name: 'Google Meet', category: 'communication', description: 'Google Meet video calls, recordings, calendar integration.', capabilities: ['Video Calls', 'Recordings', 'Calendar'], authMethods: ['oauth2'], regions: ['global'], certified: true, popularity: 88, syncIntervalDefault: '15m', realTime: false },
  { key: 'comm.telegram', provider: 'Telegram', name: 'Telegram', category: 'communication', description: 'Telegram bots, channels, groups, messages, media.', capabilities: ['Bots', 'Channels', 'Groups', 'Media'], authMethods: ['bearer'], regions: ['global'], certified: true, popularity: 65, syncIntervalDefault: 'realtime', realTime: true },
  { key: 'comm.voice', provider: 'Voice', name: 'Voice (Twilio/Vonage)', category: 'communication', description: 'Voice calls, IVR, call recording, transcription via Twilio/Vonage.', capabilities: ['Voice Calls', 'IVR', 'Recording', 'Transcription'], authMethods: ['api_key', 'bearer'], regions: ['global'], certified: true, popularity: 60, syncIntervalDefault: 'realtime', realTime: true },
  { key: 'comm.push', provider: 'Push Notifications', name: 'Push (FCM/APNs)', category: 'communication', description: 'Mobile & web push notifications via Firebase Cloud Messaging, APNs, Web Push.', capabilities: ['Mobile Push', 'Web Push', 'Topics', 'Segmented'], authMethods: ['api_key', 'certificate'], regions: ['global'], certified: true, popularity: 80, syncIntervalDefault: 'realtime', realTime: true },
  { key: 'comm.aiphone', provider: 'AI Phone', name: 'AI Phone Calls', category: 'communication', description: 'AI-powered outbound/inbound phone calls — collections, reminders, support.', capabilities: ['AI Outbound', 'AI Inbound', 'Collections', 'Reminders', 'Support'], authMethods: ['api_key', 'bearer'], regions: ['global'], certified: true, popularity: 55, syncIntervalDefault: 'realtime', realTime: true },
];

// ─── CLOUD CONNECTIVITY™ ─────────────────────────────────────────────────────────
const CLOUD_CONNECTORS: ConnectorDefinition[] = [
  { key: 'cloud.gcp', provider: 'Google Cloud', name: 'Google Cloud Platform', category: 'cloud', description: 'Compute, storage, BigQuery, Cloud SQL, Cloud Functions, IAM, billing.', capabilities: ['Compute', 'Storage', 'BigQuery', 'Cloud SQL', 'Functions', 'IAM', 'Billing'], authMethods: ['oauth2', 'certificate', 'api_key'], regions: ['global'], certified: true, popularity: 90, syncIntervalDefault: '15m', realTime: false },
  { key: 'cloud.aws', provider: 'AWS', name: 'Amazon Web Services', category: 'cloud', description: 'EC2, S3, RDS, Lambda, IAM, CloudWatch, billing, cost optimization.', capabilities: ['EC2', 'S3', 'RDS', 'Lambda', 'IAM', 'CloudWatch', 'Billing'], authMethods: ['api_key', 'certificate'], regions: ['global'], certified: true, popularity: 95, syncIntervalDefault: '15m', realTime: false },
  { key: 'cloud.azure', provider: 'Azure', name: 'Microsoft Azure', category: 'cloud', description: 'VMs, Blob Storage, Azure SQL, Functions, Entra ID, billing.', capabilities: ['VMs', 'Blob Storage', 'Azure SQL', 'Functions', 'Entra ID', 'Billing'], authMethods: ['oauth2', 'certificate'], regions: ['global'], certified: true, popularity: 88, syncIntervalDefault: '15m', realTime: false },
  { key: 'cloud.cloudflare', provider: 'Cloudflare', name: 'Cloudflare', category: 'cloud', description: 'CDN, DNS, Workers, R2 storage, D1 database, Zero Trust.', capabilities: ['CDN', 'DNS', 'Workers', 'R2', 'D1', 'Zero Trust'], authMethods: ['api_key', 'bearer'], regions: ['global'], certified: true, popularity: 85, syncIntervalDefault: '15m', realTime: false },
  { key: 'cloud.supabase', provider: 'Supabase', name: 'Supabase', category: 'cloud', description: 'Postgres, Auth, Realtime, Storage, Edge Functions.', capabilities: ['Postgres', 'Auth', 'Realtime', 'Storage', 'Edge Functions'], authMethods: ['api_key', 'bearer'], regions: ['global'], certified: true, popularity: 78, syncIntervalDefault: '15m', realTime: true },
  { key: 'cloud.firebase', provider: 'Firebase', name: 'Firebase', category: 'cloud', description: 'Firestore, Auth, Cloud Functions, Hosting, Storage, Messaging.', capabilities: ['Firestore', 'Auth', 'Functions', 'Hosting', 'Storage', 'Messaging'], authMethods: ['oauth2', 'certificate'], regions: ['global'], certified: true, popularity: 92, syncIntervalDefault: '15m', realTime: true },
  { key: 'cloud.vercel', provider: 'Vercel', name: 'Vercel', category: 'cloud', description: 'Frontend deployments, edge functions, analytics, logs.', capabilities: ['Deployments', 'Edge Functions', 'Analytics', 'Logs'], authMethods: ['bearer'], regions: ['global'], certified: true, popularity: 82, syncIntervalDefault: '15m', realTime: false },
  { key: 'cloud.netlify', provider: 'Netlify', name: 'Netlify', category: 'cloud', description: 'Static sites, serverless functions, forms, identity.', capabilities: ['Sites', 'Functions', 'Forms', 'Identity'], authMethods: ['oauth2', 'bearer'], regions: ['global'], certified: true, popularity: 70, syncIntervalDefault: '15m', realTime: false },
  { key: 'cloud.docker', provider: 'Docker', name: 'Docker Hub', category: 'cloud', description: 'Container registry, image builds, vulnerability scanning.', capabilities: ['Registry', 'Builds', 'Scanning'], authMethods: ['bearer', 'api_key'], regions: ['global'], certified: true, popularity: 80, syncIntervalDefault: '1h', realTime: false },
  { key: 'cloud.k8s', provider: 'Kubernetes', name: 'Kubernetes', category: 'cloud', description: 'Cluster management, deployments, services, ingress, HPA, RBAC.', capabilities: ['Clusters', 'Deployments', 'Services', 'Ingress', 'HPA', 'RBAC'], authMethods: ['certificate', 'oauth2'], regions: ['global'], certified: true, popularity: 82, syncIntervalDefault: '15m', realTime: false },
  { key: 'cloud.github', provider: 'GitHub', name: 'GitHub', category: 'cloud', description: 'Repositories, actions, issues, PRs, packages, secrets, codespaces.', capabilities: ['Repos', 'Actions', 'Issues', 'PRs', 'Packages', 'Codespaces'], authMethods: ['oauth2', 'bearer'], regions: ['global'], certified: true, popularity: 96, syncIntervalDefault: '15m', realTime: true },
  { key: 'cloud.gitlab', provider: 'GitLab', name: 'GitLab', category: 'cloud', description: 'Repos, CI/CD, issues, MRs, registry, security scanning.', capabilities: ['Repos', 'CI/CD', 'Issues', 'MRs', 'Registry', 'Security'], authMethods: ['oauth2', 'bearer'], regions: ['global'], certified: true, popularity: 78, syncIntervalDefault: '15m', realTime: true },
  { key: 'cloud.bitbucket', provider: 'Bitbucket', name: 'Bitbucket', category: 'cloud', description: 'Repos, pipelines, PRs, Jira integration.', capabilities: ['Repos', 'Pipelines', 'PRs', 'Jira'], authMethods: ['oauth2', 'bearer'], regions: ['global'], certified: true, popularity: 65, syncIntervalDefault: '15m', realTime: false },
];

// ─── ERP CONNECTORS™ ─────────────────────────────────────────────────────────────
const ERP_CONNECTORS: ConnectorDefinition[] = [
  { key: 'erp.sap', provider: 'SAP', name: 'SAP ERP / S/4HANA', category: 'erp', description: 'SAP modules — FI, CO, MM, SD, HR, PP, PM, integration via OData.', capabilities: ['FI', 'CO', 'MM', 'SD', 'HR', 'PP', 'PM', 'OData'], authMethods: ['oauth2', 'basic', 'certificate'], regions: ['global'], certified: true, popularity: 88, syncIntervalDefault: '15m', realTime: false },
  { key: 'erp.oracle', provider: 'Oracle ERP', name: 'Oracle ERP Cloud', category: 'erp', description: 'Oracle ERP — GL, AP, AR, FA, Projects, Procurement, SCM.', capabilities: ['GL', 'AP', 'AR', 'FA', 'Projects', 'Procurement', 'SCM'], authMethods: ['oauth2', 'basic'], regions: ['global'], certified: true, popularity: 80, syncIntervalDefault: '15m', realTime: false },
  { key: 'erp.dynamics', provider: 'Microsoft Dynamics', name: 'Microsoft Dynamics 365', category: 'erp', description: 'Finance, operations, supply chain, sales, customer service.', capabilities: ['Finance', 'Operations', 'Supply Chain', 'Sales', 'Service'], authMethods: ['oauth2'], regions: ['global'], certified: true, popularity: 82, syncIntervalDefault: '15m', realTime: false },
  { key: 'erp.odoo', provider: 'Odoo', name: 'Odoo ERP', category: 'erp', description: 'Open-source ERP — accounting, inventory, sales, HR, manufacturing, CRM.', capabilities: ['Accounting', 'Inventory', 'Sales', 'HR', 'Manufacturing', 'CRM'], authMethods: ['api_key', 'oauth2'], regions: ['global'], certified: true, popularity: 78, syncIntervalDefault: '15m', realTime: false },
  { key: 'erp.zoho', provider: 'Zoho One', name: 'Zoho One Suite', category: 'erp', description: 'Zoho Books, Inventory, People, CRM, Projects — full business suite.', capabilities: ['Books', 'Inventory', 'People', 'CRM', 'Projects'], authMethods: ['oauth2'], regions: ['global'], certified: true, popularity: 80, syncIntervalDefault: '15m', realTime: false },
  { key: 'erp.erpnext', provider: 'ERPNext', name: 'ERPNext (Frappe)', category: 'erp', description: 'Open-source ERP — accounting, stock, HR, manufacturing, projects.', capabilities: ['Accounting', 'Stock', 'HR', 'Manufacturing', 'Projects'], authMethods: ['api_key', 'oauth2'], regions: ['global'], certified: true, popularity: 60, syncIntervalDefault: '15m', realTime: false },
  { key: 'erp.tally', provider: 'Tally', name: 'Tally Prime', category: 'erp', description: 'Tally — sales, purchases, ledger, vouchers, GST, TDS, payroll.', capabilities: ['Sales', 'Purchases', 'Ledger', 'GST', 'TDS', 'Payroll'], authMethods: ['api_key', 'oauth2'], regions: ['IN'], certified: true, popularity: 95, syncIntervalDefault: '15m', realTime: false },
  { key: 'erp.busy', provider: 'Busy', name: 'Busy Accounting', category: 'erp', description: 'Busy — accounting, inventory, GST, invoicing, MIS reports.', capabilities: ['Accounting', 'Inventory', 'GST', 'Invoicing', 'MIS'], authMethods: ['api_key'], regions: ['IN'], certified: true, popularity: 70, syncIntervalDefault: '15m', realTime: false },
  { key: 'erp.marg', provider: 'Marg', name: 'Marg ERP', category: 'erp', description: 'Marg — accounting, inventory, pharmacy, GST, billing.', capabilities: ['Accounting', 'Inventory', 'Pharmacy', 'GST', 'Billing'], authMethods: ['api_key'], regions: ['IN'], certified: true, popularity: 65, syncIntervalDefault: '15m', realTime: false },
  { key: 'erp.focus', provider: 'Focus ERP', name: 'Focus ERP', category: 'erp', description: 'Focus — accounting, inventory, GST, multi-branch, manufacturing.', capabilities: ['Accounting', 'Inventory', 'GST', 'Multi-Branch', 'Manufacturing'], authMethods: ['api_key'], regions: ['IN'], certified: true, popularity: 55, syncIntervalDefault: '15m', realTime: false },
];

// ─── CRM CONNECTORS™ ─────────────────────────────────────────────────────────────
const CRM_CONNECTORS: ConnectorDefinition[] = [
  { key: 'crm.salesforce', provider: 'Salesforce', name: 'Salesforce CRM', category: 'crm', description: 'Leads, accounts, contacts, opportunities, cases, campaigns, custom objects.', capabilities: ['Leads', 'Accounts', 'Contacts', 'Opportunities', 'Cases', 'Campaigns'], authMethods: ['oauth2'], regions: ['global'], certified: true, popularity: 95, syncIntervalDefault: '15m', realTime: true },
  { key: 'crm.hubspot', provider: 'HubSpot', name: 'HubSpot CRM', category: 'crm', description: 'Contacts, companies, deals, tickets, marketing, service hub.', capabilities: ['Contacts', 'Companies', 'Deals', 'Tickets', 'Marketing', 'Service'], authMethods: ['oauth2'], regions: ['global'], certified: true, popularity: 90, syncIntervalDefault: '15m', realTime: true },
  { key: 'crm.zoho', provider: 'Zoho CRM', name: 'Zoho CRM', category: 'crm', description: 'Leads, contacts, deals, accounts, campaigns, workflows.', capabilities: ['Leads', 'Contacts', 'Deals', 'Accounts', 'Campaigns', 'Workflows'], authMethods: ['oauth2'], regions: ['global'], certified: true, popularity: 85, syncIntervalDefault: '15m', realTime: false },
  { key: 'crm.freshsales', provider: 'Freshsales', name: 'Freshsales CRM', category: 'crm', description: 'Leads, contacts, deals, sequences, AI insights, phone.', capabilities: ['Leads', 'Contacts', 'Deals', 'Sequences', 'AI Insights'], authMethods: ['oauth2', 'api_key'], regions: ['global'], certified: true, popularity: 70, syncIntervalDefault: '15m', realTime: false },
  { key: 'crm.pipedrive', provider: 'Pipedrive', name: 'Pipedrive CRM', category: 'crm', description: 'Pipeline deals, activities, contacts, automation.', capabilities: ['Pipeline', 'Activities', 'Contacts', 'Automation'], authMethods: ['oauth2', 'api_key'], regions: ['global'], certified: true, popularity: 72, syncIntervalDefault: '15m', realTime: false },
  { key: 'crm.monday', provider: 'Monday', name: 'Monday.com', category: 'crm', description: 'Work OS — boards, items, dashboards, automations, CRM template.', capabilities: ['Boards', 'Items', 'Dashboards', 'Automations', 'CRM'], authMethods: ['oauth2', 'api_key'], regions: ['global'], certified: true, popularity: 75, syncIntervalDefault: '15m', realTime: false },
  { key: 'crm.clickup', provider: 'ClickUp', name: 'ClickUp', category: 'crm', description: 'Tasks, projects, docs, goals, CRM template, time tracking.', capabilities: ['Tasks', 'Projects', 'Docs', 'Goals', 'CRM', 'Time Tracking'], authMethods: ['oauth2'], regions: ['global'], certified: true, popularity: 78, syncIntervalDefault: '15m', realTime: false },
  { key: 'crm.notion', provider: 'Notion', name: 'Notion', category: 'crm', description: 'Databases, pages, blocks, comments, custom CRM templates.', capabilities: ['Databases', 'Pages', 'Blocks', 'Comments'], authMethods: ['oauth2', 'bearer'], regions: ['global'], certified: true, popularity: 85, syncIntervalDefault: '15m', realTime: false },
  { key: 'crm.airtable', provider: 'Airtable', name: 'Airtable', category: 'crm', description: 'Bases, tables, records, attachments, automations, CRM templates.', capabilities: ['Bases', 'Tables', 'Records', 'Attachments', 'Automations'], authMethods: ['oauth2', 'api_key'], regions: ['global'], certified: true, popularity: 80, syncIntervalDefault: '15m', realTime: false },
];

// ─── ACCOUNTING CONNECTORS™ ──────────────────────────────────────────────────────
const ACCOUNTING_CONNECTORS: ConnectorDefinition[] = [
  { key: 'acc.quickbooks', provider: 'QuickBooks', name: 'QuickBooks Online', category: 'accounting', description: 'Invoices, expenses, customers, vendors, banking, reports.', capabilities: ['Invoices', 'Expenses', 'Customers', 'Vendors', 'Banking', 'Reports'], authMethods: ['oauth2'], regions: ['global'], certified: true, popularity: 88, syncIntervalDefault: '15m', realTime: false },
  { key: 'acc.xero', provider: 'Xero', name: 'Xero Accounting', category: 'accounting', description: 'Invoices, bills, bank, contacts, payroll, reports.', capabilities: ['Invoices', 'Bills', 'Bank', 'Contacts', 'Payroll', 'Reports'], authMethods: ['oauth2'], regions: ['global'], certified: true, popularity: 80, syncIntervalDefault: '15m', realTime: false },
  { key: 'acc.zohobooks', provider: 'Zoho Books', name: 'Zoho Books', category: 'accounting', description: 'Invoices, expenses, inventory, banking, GST, projects.', capabilities: ['Invoices', 'Expenses', 'Inventory', 'Banking', 'GST', 'Projects'], authMethods: ['oauth2'], regions: ['global'], certified: true, popularity: 78, syncIntervalDefault: '15m', realTime: false },
  { key: 'acc.freshbooks', provider: 'FreshBooks', name: 'FreshBooks', category: 'accounting', description: 'Invoices, time tracking, expenses, estimates, payments.', capabilities: ['Invoices', 'Time Tracking', 'Expenses', 'Estimates', 'Payments'], authMethods: ['oauth2'], regions: ['global'], certified: true, popularity: 65, syncIntervalDefault: '15m', realTime: false },
  { key: 'acc.tally', provider: 'Tally', name: 'Tally Prime (Accounting)', category: 'accounting', description: 'Accounting, vouchers, ledger, GST, TDS — same as ERP entry, accounting focus.', capabilities: ['Accounting', 'Vouchers', 'Ledger', 'GST', 'TDS'], authMethods: ['api_key'], regions: ['IN'], certified: true, popularity: 95, syncIntervalDefault: '15m', realTime: false },
  { key: 'acc.busy', provider: 'Busy', name: 'Busy Accounting', category: 'accounting', description: 'Accounting, inventory, GST, VAT, service tax.', capabilities: ['Accounting', 'Inventory', 'GST', 'VAT'], authMethods: ['api_key'], regions: ['IN'], certified: true, popularity: 70, syncIntervalDefault: '15m', realTime: false },
  { key: 'acc.marg', provider: 'Marg', name: 'Marg Accounting', category: 'accounting', description: 'Accounting, inventory, billing, GST for retail/pharma.', capabilities: ['Accounting', 'Inventory', 'Billing', 'GST'], authMethods: ['api_key'], regions: ['IN'], certified: true, popularity: 65, syncIntervalDefault: '15m', realTime: false },
  { key: 'acc.wave', provider: 'Wave', name: 'Wave Accounting', category: 'accounting', description: 'Free accounting, invoicing, receipts, payroll.', capabilities: ['Accounting', 'Invoicing', 'Receipts', 'Payroll'], authMethods: ['oauth2'], regions: ['global'], certified: true, popularity: 55, syncIntervalDefault: '15m', realTime: false },
  { key: 'acc.oraclefin', provider: 'Oracle Financials', name: 'Oracle Financials Cloud', category: 'accounting', description: 'Enterprise GL, AP, AR, FA, expenses, revenue management.', capabilities: ['GL', 'AP', 'AR', 'FA', 'Expenses', 'Revenue'], authMethods: ['oauth2'], regions: ['global'], certified: true, popularity: 70, syncIntervalDefault: '15m', realTime: false },
];

// ─── AI PROVIDER FABRIC™ ─────────────────────────────────────────────────────────
const AI_CONNECTORS: ConnectorDefinition[] = [
  { key: 'ai.openai', provider: 'OpenAI', name: 'OpenAI', category: 'ai', description: 'GPT-4o, o1, GPT-4 Turbo, Assistants, DALL-E, Whisper, embeddings.', capabilities: ['GPT-4o', 'o1', 'GPT-4 Turbo', 'Assistants', 'DALL-E', 'Whisper', 'Embeddings'], authMethods: ['bearer'], regions: ['global'], certified: true, popularity: 99, syncIntervalDefault: 'realtime', realTime: true },
  { key: 'ai.anthropic', provider: 'Anthropic', name: 'Anthropic Claude', category: 'ai', description: 'Claude 3.5 Sonnet, Opus, Haiku — vision, long context, tool use.', capabilities: ['Claude 3.5 Sonnet', 'Opus', 'Haiku', 'Vision', 'Tool Use'], authMethods: ['api_key', 'bearer'], regions: ['global'], certified: true, popularity: 95, syncIntervalDefault: 'realtime', realTime: true },
  { key: 'ai.gemini', provider: 'Google Gemini', name: 'Google Gemini', category: 'ai', description: 'Gemini 1.5 Pro/Flash, Imagen, Codey, multimodal, long context.', capabilities: ['Gemini 1.5 Pro', 'Flash', 'Imagen', 'Codey', 'Multimodal'], authMethods: ['api_key', 'oauth2'], regions: ['global'], certified: true, popularity: 92, syncIntervalDefault: 'realtime', realTime: true },
  { key: 'ai.xai', provider: 'xAI', name: 'xAI (Grok)', category: 'ai', description: 'Grok-2, Grok-2 Vision, real-time data integration via X.', capabilities: ['Grok-2', 'Grok-2 Vision', 'Real-time'], authMethods: ['bearer'], regions: ['global'], certified: true, popularity: 70, syncIntervalDefault: 'realtime', realTime: true },
  { key: 'ai.mistral', provider: 'Mistral', name: 'Mistral AI', category: 'ai', description: 'Mistral Large, Codestral, Pixtral, embeddings, function calling.', capabilities: ['Mistral Large', 'Codestral', 'Pixtral', 'Function Calling'], authMethods: ['api_key', 'bearer'], regions: ['global'], certified: true, popularity: 75, syncIntervalDefault: 'realtime', realTime: true },
  { key: 'ai.deepseek', provider: 'DeepSeek', name: 'DeepSeek', category: 'ai', description: 'DeepSeek V3, R1 reasoning model, Coder — open-weight, low cost.', capabilities: ['DeepSeek V3', 'R1', 'Coder'], authMethods: ['api_key', 'bearer'], regions: ['global'], certified: true, popularity: 80, syncIntervalDefault: 'realtime', realTime: true },
  { key: 'ai.perplexity', provider: 'Perplexity', name: 'Perplexity API', category: 'ai', description: 'Online LLMs with citations — Sonar, sonar-pro, sonar-reasoning.', capabilities: ['Sonar', 'Online Search', 'Citations'], authMethods: ['bearer'], regions: ['global'], certified: true, popularity: 72, syncIntervalDefault: 'realtime', realTime: true },
  { key: 'ai.llama', provider: 'Meta Llama', name: 'Meta Llama', category: 'ai', description: 'Llama 3.1, 3.2, 3.3 — open weights, hosted via Together/Fireworks/Replicate.', capabilities: ['Llama 3.1', '3.2', '3.3', 'Vision', 'Tool Use'], authMethods: ['api_key', 'bearer'], regions: ['global'], certified: true, popularity: 78, syncIntervalDefault: 'realtime', realTime: true },
  { key: 'ai.nvidia', provider: 'NVIDIA NIM', name: 'NVIDIA NIM', category: 'ai', description: 'NVIDIA-hosted open models — Llama, Mistral, Qwen via NIM microservices.', capabilities: ['Llama', 'Mistral', 'Qwen', 'NIM'], authMethods: ['api_key', 'bearer'], regions: ['global'], certified: true, popularity: 65, syncIntervalDefault: 'realtime', realTime: true },
  { key: 'ai.azureopenai', provider: 'Azure OpenAI', name: 'Azure OpenAI Service', category: 'ai', description: 'Enterprise OpenAI on Azure — GPT-4, Assistants, content filtering, VNet.', capabilities: ['GPT-4', 'Assistants', 'Content Filtering', 'VNet'], authMethods: ['api_key', 'oauth2'], regions: ['global'], certified: true, popularity: 85, syncIntervalDefault: 'realtime', realTime: true },
];

// ─── PAYMENT FABRIC™ ─────────────────────────────────────────────────────────────
const PAYMENT_CONNECTORS: ConnectorDefinition[] = [
  { key: 'pay.razorpay', provider: 'Razorpay', name: 'Razorpay', category: 'payments', description: 'Payment gateway, UPI, cards, netbanking, payouts, subscriptions, smart collect.', capabilities: ['Gateway', 'UPI', 'Cards', 'Netbanking', 'Payouts', 'Subscriptions', 'Smart Collect'], authMethods: ['api_key', 'oauth2'], regions: ['IN'], certified: true, popularity: 95, syncIntervalDefault: '5m', realTime: true },
  { key: 'pay.stripe', provider: 'Stripe', name: 'Stripe', category: 'payments', description: 'Cards, ACH, SEPA, wallets, subscriptions, Connect, billing, invoicing.', capabilities: ['Cards', 'ACH', 'SEPA', 'Wallets', 'Connect', 'Billing'], authMethods: ['bearer', 'oauth2'], regions: ['global'], certified: true, popularity: 96, syncIntervalDefault: '5m', realTime: true },
  { key: 'pay.cashfree', provider: 'Cashfree', name: 'Cashfree Payments', category: 'payments', description: 'Payment gateway, payouts, easy split, vendor payouts, international.', capabilities: ['Gateway', 'Payouts', 'Easy Split', 'Vendor Payouts'], authMethods: ['api_key'], regions: ['IN'], certified: true, popularity: 80, syncIntervalDefault: '5m', realTime: true },
  { key: 'pay.phonepe', provider: 'PhonePe', name: 'PhonePe', category: 'payments', description: 'UPI, payment gateway, switch, merchant settlements.', capabilities: ['UPI', 'Gateway', 'Switch', 'Settlements'], authMethods: ['api_key', 'certificate'], regions: ['IN'], certified: true, popularity: 88, syncIntervalDefault: '5m', realTime: true },
  { key: 'pay.paytm', provider: 'Paytm', name: 'Paytm Payment Gateway', category: 'payments', description: 'UPI, cards, wallets, EMI, BNPL, payouts.', capabilities: ['UPI', 'Cards', 'Wallets', 'EMI', 'BNPL', 'Payouts'], authMethods: ['api_key'], regions: ['IN'], certified: true, popularity: 78, syncIntervalDefault: '5m', realTime: true },
  { key: 'pay.payu', provider: 'PayU', name: 'PayU', category: 'payments', description: 'Payment gateway, payouts, BNPL (LazyPay), international.', capabilities: ['Gateway', 'Payouts', 'BNPL', 'International'], authMethods: ['api_key'], regions: ['IN'], certified: true, popularity: 75, syncIntervalDefault: '5m', realTime: true },
  { key: 'pay.ccavenue', provider: 'CCAvenue', name: 'CCAvenue', category: 'payments', description: 'Multi-currency payment gateway, cards, netbanking, UPI.', capabilities: ['Multi-currency', 'Cards', 'Netbanking', 'UPI'], authMethods: ['api_key'], regions: ['IN'], certified: true, popularity: 70, syncIntervalDefault: '5m', realTime: true },
  { key: 'pay.billdesk', provider: 'BillDesk', name: 'BillDesk', category: 'payments', description: 'Bill payments, payment gateway, BBPS, B2B collections.', capabilities: ['Bill Payments', 'Gateway', 'BBPS', 'B2B Collections'], authMethods: ['api_key'], regions: ['IN'], certified: true, popularity: 68, syncIntervalDefault: '5m', realTime: true },
  { key: 'pay.adyen', provider: 'Adyen', name: 'Adyen', category: 'payments', description: 'Global acquiring, unified commerce, issuing, terminals, B2B.', capabilities: ['Acquiring', 'Unified Commerce', 'Issuing', 'Terminals'], authMethods: ['api_key', 'bearer'], regions: ['global'], certified: true, popularity: 75, syncIntervalDefault: '5m', realTime: true },
  { key: 'pay.paypal', provider: 'PayPal', name: 'PayPal', category: 'payments', description: 'Global payments, Payouts, invoicing, subscriptions, Braintree.', capabilities: ['Global', 'Payouts', 'Invoicing', 'Subscriptions'], authMethods: ['oauth2', 'api_key'], regions: ['global'], certified: true, popularity: 85, syncIntervalDefault: '5m', realTime: true },
  { key: 'pay.square', provider: 'Square', name: 'Square', category: 'payments', description: 'In-person payments, online payments, POS, invoicing, payouts.', capabilities: ['In-Person', 'Online', 'POS', 'Invoicing'], authMethods: ['oauth2'], regions: ['global'], certified: true, popularity: 72, syncIntervalDefault: '5m', realTime: true },
];

// ─── STORAGE / E-COMMERCE / LOGISTICS / IoT / POS / ANALYTICS / DEVTOOLS ─────────
const STORAGE_CONNECTORS: ConnectorDefinition[] = [
  { key: 'storage.s3', provider: 'AWS S3', name: 'Amazon S3', category: 'storage', description: 'Object storage, lifecycle, versioning, replication, Glacier.', capabilities: ['Object Storage', 'Lifecycle', 'Versioning', 'Replication'], authMethods: ['api_key', 'certificate'], regions: ['global'], certified: true, popularity: 95, syncIntervalDefault: '15m', realTime: false },
  { key: 'storage.gcs', provider: 'Google Cloud Storage', name: 'Google Cloud Storage', category: 'storage', description: 'Object storage, nearline, coldline, archive, signed URLs.', capabilities: ['Object Storage', 'Nearline', 'Coldline', 'Archive'], authMethods: ['oauth2', 'certificate'], regions: ['global'], certified: true, popularity: 88, syncIntervalDefault: '15m', realTime: false },
  { key: 'storage.azure_blob', provider: 'Azure Blob', name: 'Azure Blob Storage', category: 'storage', description: 'Block, append, page blobs; hot/cool/archive tiers.', capabilities: ['Block Blob', 'Append', 'Page Blob', 'Tiers'], authMethods: ['oauth2', 'api_key'], regions: ['global'], certified: true, popularity: 82, syncIntervalDefault: '15m', realTime: false },
  { key: 'storage.dropbox', provider: 'Dropbox', name: 'Dropbox', category: 'storage', description: 'File storage, sharing, paper, team folders.', capabilities: ['Files', 'Sharing', 'Paper', 'Team Folders'], authMethods: ['oauth2'], regions: ['global'], certified: true, popularity: 75, syncIntervalDefault: '1h', realTime: false },
  { key: 'storage.googledrive', provider: 'Google Drive', name: 'Google Drive', category: 'storage', description: 'Personal & shared drives, docs, sheets, slides, forms.', capabilities: ['Files', 'Shared Drives', 'Docs', 'Sheets', 'Slides'], authMethods: ['oauth2'], regions: ['global'], certified: true, popularity: 92, syncIntervalDefault: '1h', realTime: false },
  { key: 'storage.onedrive', provider: 'OneDrive', name: 'Microsoft OneDrive', category: 'storage', description: 'Personal & business file storage, SharePoint integration.', capabilities: ['Files', 'SharePoint', 'Business'], authMethods: ['oauth2'], regions: ['global'], certified: true, popularity: 80, syncIntervalDefault: '1h', realTime: false },
];

const ECOMMERCE_CONNECTORS: ConnectorDefinition[] = [
  { key: 'ecom.shopify', provider: 'Shopify', name: 'Shopify', category: 'ecommerce', description: 'Products, orders, customers, inventory, fulfillments, payouts.', capabilities: ['Products', 'Orders', 'Customers', 'Inventory', 'Fulfillments'], authMethods: ['oauth2', 'api_key'], regions: ['global'], certified: true, popularity: 92, syncIntervalDefault: '15m', realTime: true },
  { key: 'ecom.woocommerce', provider: 'WooCommerce', name: 'WooCommerce', category: 'ecommerce', description: 'WordPress commerce — products, orders, customers, coupons.', capabilities: ['Products', 'Orders', 'Customers', 'Coupons'], authMethods: ['api_key', 'oauth2'], regions: ['global'], certified: true, popularity: 78, syncIntervalDefault: '15m', realTime: false },
  { key: 'ecom.magento', provider: 'Magento', name: 'Magento / Adobe Commerce', category: 'ecommerce', description: 'Enterprise commerce — products, orders, customers, CMS.', capabilities: ['Products', 'Orders', 'Customers', 'CMS'], authMethods: ['oauth2', 'api_key'], regions: ['global'], certified: true, popularity: 65, syncIntervalDefault: '15m', realTime: false },
  { key: 'ecom.amazon', provider: 'Amazon SP-API', name: 'Amazon Seller', category: 'ecommerce', description: 'Listings, orders, FBA inventory, settlements, reports.', capabilities: ['Listings', 'Orders', 'FBA', 'Settlements', 'Reports'], authMethods: ['oauth2'], regions: ['global'], certified: true, popularity: 80, syncIntervalDefault: '15m', realTime: false },
  { key: 'ecom.flipkart', provider: 'Flipkart', name: 'Flipkart Seller', category: 'ecommerce', description: 'Listings, orders, fulfillments, settlements, returns.', capabilities: ['Listings', 'Orders', 'Fulfillments', 'Settlements', 'Returns'], authMethods: ['oauth2', 'api_key'], regions: ['IN'], certified: true, popularity: 70, syncIntervalDefault: '15m', realTime: false },
  { key: 'ecom.meesho', provider: 'Meesho', name: 'Meesho Seller', category: 'ecommerce', description: 'Listings, orders, settlements, returns.', capabilities: ['Listings', 'Orders', 'Settlements', 'Returns'], authMethods: ['api_key'], regions: ['IN'], certified: true, popularity: 60, syncIntervalDefault: '15m', realTime: false },
];

const LOGISTICS_CONNECTORS: ConnectorDefinition[] = [
  { key: 'log.delhivery', provider: 'Delhivery', name: 'Delhivery', category: 'logistics', description: 'Shipments, tracking, COD remittance, NDR, RTO.', capabilities: ['Shipments', 'Tracking', 'COD', 'NDR', 'RTO'], authMethods: ['api_key', 'bearer'], regions: ['IN'], certified: true, popularity: 85, syncIntervalDefault: '15m', realTime: true },
  { key: 'log.bluedart', provider: 'BlueDart', name: 'BlueDart', category: 'logistics', description: 'Domestic & international courier, tracking, pickup.', capabilities: ['Courier', 'Tracking', 'Pickup', 'International'], authMethods: ['api_key'], regions: ['IN'], certified: true, popularity: 75, syncIntervalDefault: '15m', realTime: false },
  { key: 'log.dtdc', provider: 'DTDC', name: 'DTDC', category: 'logistics', description: 'Domestic & international courier, tracking.', capabilities: ['Courier', 'Tracking', 'International'], authMethods: ['api_key'], regions: ['IN'], certified: true, popularity: 65, syncIntervalDefault: '15m', realTime: false },
  { key: 'log.ekart', provider: 'Ekart', name: 'Ekart Logistics', category: 'logistics', description: 'Last-mile delivery, tracking, COD.', capabilities: ['Last-mile', 'Tracking', 'COD'], authMethods: ['api_key'], regions: ['IN'], certified: true, popularity: 60, syncIntervalDefault: '15m', realTime: false },
  { key: 'log.fedex', provider: 'FedEx', name: 'FedEx', category: 'logistics', description: 'Global shipping, tracking, customs.', capabilities: ['Global Shipping', 'Tracking', 'Customs'], authMethods: ['oauth2', 'api_key'], regions: ['global'], certified: true, popularity: 80, syncIntervalDefault: '15m', realTime: false },
  { key: 'log.ups', provider: 'UPS', name: 'UPS', category: 'logistics', description: 'Global shipping, tracking, returns, freight.', capabilities: ['Global Shipping', 'Tracking', 'Returns', 'Freight'], authMethods: ['oauth2', 'api_key'], regions: ['global'], certified: true, popularity: 78, syncIntervalDefault: '15m', realTime: false },
  { key: 'log.shiprocket', provider: 'Shiprocket', name: 'Shiprocket', category: 'logistics', description: 'Multi-carrier aggregator, orders, tracking, returns.', capabilities: ['Multi-Carrier', 'Orders', 'Tracking', 'Returns'], authMethods: ['api_key', 'bearer'], regions: ['IN'], certified: true, popularity: 82, syncIntervalDefault: '15m', realTime: true },
];

const IOT_CONNECTORS: ConnectorDefinition[] = [
  { key: 'iot.aws_iot', provider: 'AWS IoT', name: 'AWS IoT Core', category: 'iot', description: 'MQTT, device shadows, rules, jobs, fleet indexing.', capabilities: ['MQTT', 'Device Shadows', 'Rules', 'Jobs'], authMethods: ['certificate', 'api_key'], regions: ['global'], certified: true, popularity: 80, syncIntervalDefault: '5m', realTime: true },
  { key: 'iot.azure_iot', provider: 'Azure IoT', name: 'Azure IoT Hub', category: 'iot', description: 'Device-to-cloud, twins, edge, DPS, routing.', capabilities: ['Device-to-Cloud', 'Twins', 'Edge', 'DPS'], authMethods: ['certificate', 'oauth2'], regions: ['global'], certified: true, popularity: 75, syncIntervalDefault: '5m', realTime: true },
  { key: 'iot.gcp_iot', provider: 'Google IoT', name: 'Google Cloud IoT', category: 'iot', description: 'MQTT bridge, device registry, configs, commands.', capabilities: ['MQTT', 'Device Registry', 'Configs', 'Commands'], authMethods: ['oauth2', 'certificate'], regions: ['global'], certified: true, popularity: 60, syncIntervalDefault: '5m', realTime: true },
  { key: 'iot.tuya', provider: 'Tuya', name: 'Tuya IoT Platform', category: 'iot', description: 'Smart devices, scenes, automations, OEM.', capabilities: ['Smart Devices', 'Scenes', 'Automations'], authMethods: ['api_key', 'oauth2'], regions: ['global'], certified: true, popularity: 55, syncIntervalDefault: '5m', realTime: true },
  { key: 'iot.mqtt', provider: 'MQTT Broker', name: 'MQTT / HiveMQ', category: 'iot', description: 'Generic MQTT broker — pub/sub topics, retained messages.', capabilities: ['Pub/Sub', 'Retained', 'Last-Will'], authMethods: ['certificate', 'basic'], regions: ['global'], certified: true, popularity: 65, syncIntervalDefault: '5m', realTime: true },
];

const POS_CONNECTORS: ConnectorDefinition[] = [
  { key: 'pos.square', provider: 'Square POS', name: 'Square POS', category: 'pos', description: 'In-person sales, catalog, inventory, tips, refunds.', capabilities: ['Sales', 'Catalog', 'Inventory', 'Tips', 'Refunds'], authMethods: ['oauth2'], regions: ['global'], certified: true, popularity: 80, syncIntervalDefault: '15m', realTime: true },
  { key: 'pos.toast', provider: 'Toast', name: 'Toast POS', category: 'pos', description: 'Restaurant POS, menus, orders, payments, payroll.', capabilities: ['Restaurant POS', 'Menus', 'Orders', 'Payments'], authMethods: ['oauth2'], regions: ['global'], certified: true, popularity: 70, syncIntervalDefault: '15m', realTime: false },
  { key: 'pos.clover', provider: 'Clover', name: 'Clover POS', category: 'pos', description: 'In-person POS, inventory, employees, payments.', capabilities: ['POS', 'Inventory', 'Employees', 'Payments'], authMethods: ['oauth2', 'api_key'], regions: ['global'], certified: true, popularity: 65, syncIntervalDefault: '15m', realTime: false },
  { key: 'pos.petpooja', provider: 'Petpooja', name: 'Petpooja POS', category: 'pos', description: 'Indian restaurant POS, billing, KOT, inventory.', capabilities: ['Restaurant POS', 'Billing', 'KOT', 'Inventory'], authMethods: ['api_key'], regions: ['IN'], certified: true, popularity: 60, syncIntervalDefault: '15m', realTime: false },
  { key: 'pos.posist', provider: 'Posist', name: 'Posist POS', category: 'pos', description: 'Cloud restaurant POS, menus, recipes, reporting.', capabilities: ['Cloud POS', 'Menus', 'Recipes', 'Reporting'], authMethods: ['api_key'], regions: ['IN'], certified: true, popularity: 55, syncIntervalDefault: '15m', realTime: false },
];

const ANALYTICS_CONNECTORS: ConnectorDefinition[] = [
  { key: 'analytics.ga4', provider: 'Google Analytics', name: 'Google Analytics 4', category: 'analytics', description: 'Web & app analytics, events, audiences, conversions.', capabilities: ['Web', 'App', 'Events', 'Audiences', 'Conversions'], authMethods: ['oauth2'], regions: ['global'], certified: true, popularity: 92, syncIntervalDefault: '1h', realTime: false },
  { key: 'analytics.mixpanel', provider: 'Mixpanel', name: 'Mixpanel', category: 'analytics', description: 'Product analytics, funnels, retention, cohorts.', capabilities: ['Funnels', 'Retention', 'Cohorts'], authMethods: ['api_key', 'bearer'], regions: ['global'], certified: true, popularity: 75, syncIntervalDefault: '1h', realTime: false },
  { key: 'analytics.amplitude', provider: 'Amplitude', name: 'Amplitude', category: 'analytics', description: 'Product analytics, behavioral cohorts, predictions.', capabilities: ['Behavioral', 'Cohorts', 'Predictions'], authMethods: ['api_key', 'bearer'], regions: ['global'], certified: true, popularity: 78, syncIntervalDefault: '1h', realTime: false },
  { key: 'analytics.segment', provider: 'Segment', name: 'Segment', category: 'analytics', description: 'Customer data platform, destinations, personas, traits.', capabilities: ['CDP', 'Destinations', 'Personas'], authMethods: ['api_key', 'oauth2'], regions: ['global'], certified: true, popularity: 80, syncIntervalDefault: '15m', realTime: true },
  { key: 'analytics.hotjar', provider: 'Hotjar', name: 'Hotjar', category: 'analytics', description: 'Heatmaps, session recordings, funnels, feedback.', capabilities: ['Heatmaps', 'Recordings', 'Funnels', 'Feedback'], authMethods: ['api_key'], regions: ['global'], certified: true, popularity: 70, syncIntervalDefault: '6h', realTime: false },
  { key: 'analytics.tableau', provider: 'Tableau', name: 'Tableau', category: 'analytics', description: 'Business intelligence, dashboards, embedded analytics.', capabilities: ['Dashboards', 'BI', 'Embedded'], authMethods: ['oauth2', 'api_key'], regions: ['global'], certified: true, popularity: 80, syncIntervalDefault: '1h', realTime: false },
  { key: 'analytics.powerbi', provider: 'Power BI', name: 'Microsoft Power BI', category: 'analytics', description: 'Business intelligence, dashboards, datasets, embedded.', capabilities: ['Dashboards', 'Datasets', 'Embedded'], authMethods: ['oauth2'], regions: ['global'], certified: true, popularity: 85, syncIntervalDefault: '1h', realTime: false },
  { key: 'analytics.looker', provider: 'Looker', name: 'Looker', category: 'analytics', description: 'LookML modeling, dashboards, embedded analytics.', capabilities: ['LookML', 'Dashboards', 'Embedded'], authMethods: ['oauth2', 'api_key'], regions: ['global'], certified: true, popularity: 75, syncIntervalDefault: '1h', realTime: false },
];

const DEVTOOLS_CONNECTORS: ConnectorDefinition[] = [
  { key: 'dev.jira', provider: 'Jira', name: 'Jira', category: 'devtools', description: 'Issues, sprints, boards, epics, releases, service desk.', capabilities: ['Issues', 'Sprints', 'Boards', 'Epics', 'Releases'], authMethods: ['oauth2', 'api_key'], regions: ['global'], certified: true, popularity: 90, syncIntervalDefault: '15m', realTime: true },
  { key: 'dev.linear', provider: 'Linear', name: 'Linear', category: 'devtools', description: 'Issue tracking, projects, cycles, roadmap, integrations.', capabilities: ['Issues', 'Projects', 'Cycles', 'Roadmap'], authMethods: ['api_key', 'oauth2'], regions: ['global'], certified: true, popularity: 80, syncIntervalDefault: '15m', realTime: true },
  { key: 'dev.asana', provider: 'Asana', name: 'Asana', category: 'devtools', description: 'Projects, tasks, goals, portfolios, custom fields.', capabilities: ['Projects', 'Tasks', 'Goals', 'Portfolios'], authMethods: ['oauth2'], regions: ['global'], certified: true, popularity: 78, syncIntervalDefault: '15m', realTime: false },
  { key: 'dev.trello', provider: 'Trello', name: 'Trello', category: 'devtools', description: 'Boards, lists, cards, labels, checklists, automation.', capabilities: ['Boards', 'Lists', 'Cards', 'Checklists'], authMethods: ['api_key', 'oauth2'], regions: ['global'], certified: true, popularity: 75, syncIntervalDefault: '15m', realTime: false },
  { key: 'dev.sentry', provider: 'Sentry', name: 'Sentry', category: 'devtools', description: 'Error tracking, performance, releases, source maps.', capabilities: ['Errors', 'Performance', 'Releases'], authMethods: ['api_key', 'bearer'], regions: ['global'], certified: true, popularity: 85, syncIntervalDefault: '5m', realTime: true },
  { key: 'dev.datadog', provider: 'Datadog', name: 'Datadog', category: 'devtools', description: 'Infrastructure, APM, logs, traces, synthetic monitoring.', capabilities: ['Infra', 'APM', 'Logs', 'Synthetic'], authMethods: ['api_key', 'bearer'], regions: ['global'], certified: true, popularity: 88, syncIntervalDefault: '5m', realTime: true },
  { key: 'dev.pagerduty', provider: 'PagerDuty', name: 'PagerDuty', category: 'devtools', description: 'On-call, incidents, escalations, schedules, analytics.', capabilities: ['On-call', 'Incidents', 'Escalations', 'Schedules'], authMethods: ['api_key', 'oauth2'], regions: ['global'], certified: true, popularity: 78, syncIntervalDefault: '5m', realTime: true },
  { key: 'dev.postman', provider: 'Postman', name: 'Postman', category: 'devtools', description: 'API collections, environments, tests, monitors.', capabilities: ['Collections', 'Environments', 'Tests', 'Monitors'], authMethods: ['api_key'], regions: ['global'], certified: true, popularity: 80, syncIntervalDefault: '15m', realTime: false },
];

const HRMS_CONNECTORS: ConnectorDefinition[] = [
  { key: 'hrms.bamboo', provider: 'BambooHR', name: 'BambooHR', category: 'hrms', description: 'Employee records, time-off, performance, onboarding, reports.', capabilities: ['Employees', 'Time-off', 'Performance', 'Onboarding'], authMethods: ['api_key', 'oauth2'], regions: ['global'], certified: true, popularity: 80, syncIntervalDefault: '1h', realTime: false },
  { key: 'hrms.workday', provider: 'Workday', name: 'Workday', category: 'hrms', description: 'HCM, payroll, talent, finance, planning.', capabilities: ['HCM', 'Payroll', 'Talent', 'Planning'], authMethods: ['oauth2', 'certificate'], regions: ['global'], certified: true, popularity: 78, syncIntervalDefault: '1h', realTime: false },
  { key: 'hrms.keka', provider: 'Keka', name: 'Keka HR', category: 'hrms', description: 'Indian HRMS — attendance, leave, payroll, performance.', capabilities: ['Attendance', 'Leave', 'Payroll', 'Performance'], authMethods: ['api_key', 'oauth2'], regions: ['IN'], certified: true, popularity: 70, syncIntervalDefault: '1h', realTime: false },
  { key: 'hrms.zohopeople', provider: 'Zoho People', name: 'Zoho People', category: 'hrms', description: 'HRMS — attendance, leave, timesheets, performance, cases.', capabilities: ['Attendance', 'Leave', 'Timesheets', 'Performance'], authMethods: ['oauth2'], regions: ['global'], certified: true, popularity: 72, syncIntervalDefault: '1h', realTime: false },
  { key: 'hrms.greythr', provider: 'greytHR', name: 'greytHR', category: 'hrms', description: 'Indian HR & payroll — attendance, leave, payroll, statutory.', capabilities: ['Attendance', 'Leave', 'Payroll', 'Statutory'], authMethods: ['api_key'], regions: ['IN'], certified: true, popularity: 68, syncIntervalDefault: '1h', realTime: false },
];

const PAYROLL_HR_CONNECTORS: ConnectorDefinition[] = [
  { key: 'payroll.deel', provider: 'Deel', name: 'Deel', category: 'payroll', description: 'Global payroll, EOR, contractors, compliance, payments.', capabilities: ['Global Payroll', 'EOR', 'Contractors', 'Compliance'], authMethods: ['api_key', 'oauth2'], regions: ['global'], certified: true, popularity: 75, syncIntervalDefault: '1h', realTime: false },
  { key: 'payroll.gusto', provider: 'Gusto', name: 'Gusto', category: 'payroll', description: 'US payroll, benefits, workers comp, contractor payments.', capabilities: ['Payroll', 'Benefits', 'Workers Comp'], authMethods: ['oauth2'], regions: ['US'], certified: true, popularity: 70, syncIntervalDefault: '1h', realTime: false },
  { key: 'payroll.rzp_payroll', provider: 'RazorpayX Payroll', name: 'RazorpayX Payroll', category: 'payroll', description: 'Indian payroll, statutory, insurance, advances.', capabilities: ['Payroll', 'Statutory', 'Insurance', 'Advances'], authMethods: ['api_key', 'oauth2'], regions: ['IN'], certified: true, popularity: 75, syncIntervalDefault: '1h', realTime: false },
];

// ─── Aggregate catalog ───────────────────────────────────────────────────────────
export const CONNECTOR_CATALOG: ConnectorDefinition[] = [
  ...BANKING_CONNECTORS,
  ...GOVERNMENT_CONNECTORS,
  ...COMMUNICATION_CONNECTORS,
  ...CLOUD_CONNECTORS,
  ...ERP_CONNECTORS,
  ...CRM_CONNECTORS,
  ...ACCOUNTING_CONNECTORS,
  ...AI_CONNECTORS,
  ...PAYMENT_CONNECTORS,
  ...STORAGE_CONNECTORS,
  ...ECOMMERCE_CONNECTORS,
  ...LOGISTICS_CONNECTORS,
  ...IOT_CONNECTORS,
  ...POS_CONNECTORS,
  ...ANALYTICS_CONNECTORS,
  ...DEVTOOLS_CONNECTORS,
  ...HRMS_CONNECTORS,
  ...PAYROLL_HR_CONNECTORS,
];

// Quick lookups
export const CONNECTOR_BY_KEY: Record<string, ConnectorDefinition> = Object.fromEntries(
  CONNECTOR_CATALOG.map((c) => [c.key, c])
);

export function getConnector(key: string): ConnectorDefinition | undefined {
  return CONNECTOR_BY_KEY[key];
}

export function listByCategory(category: ConnectorCategory): ConnectorDefinition[] {
  return CONNECTOR_CATALOG.filter((c) => c.category === category);
}

export const CATEGORY_COUNTS: Record<ConnectorCategory, number> = CONNECTOR_CATALOG.reduce(
  (acc, c) => {
    acc[c.category] = (acc[c.category] ?? 0) + 1;
    return acc;
  },
  {} as Record<ConnectorCategory, number>
);

export const TOTAL_CATALOG_CONNECTORS: number = CONNECTOR_CATALOG.length;
